\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={NOAA Storm Database - worst cases},
            pdfauthor={erickfis},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{longtable,booktabs}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}
  \title{NOAA Storm Database - worst cases}
  \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
  \author{erickfis}
  \preauthor{\centering\large\emph}
  \postauthor{\par}
  \predate{\centering\large\emph}
  \postdate{\par}
  \date{2017 maio, 11}


\begin{document}
\maketitle

{
\setcounter{tocdepth}{3}
\tableofcontents
}
\newpage

\section{Introduction}\label{introduction}

In this study we have analysed the NOAA Storm Database in order to
determine what are the worst natural catastrophic events, both in terms
of public health and in economic impact.

The U.S. National Oceanic and Atmospheric Administration's (NOAA) storm
database tracks characteristics of major storms and weather events in
the United States, including when and where they occur, as well as
estimates of any fatalities, injuries, and property damage.

The database currently contains data from January 1950 to January 2017,
as entered by NOAA's National Weather Service (NWS).

The database can be found on:

\url{https://www.ncdc.noaa.gov/stormevents/ftp.jsp}

RPubs version: \url{http://rpubs.com/erickfis/noaa}

GitHub version, with code included and pdf version:
\url{https://github.com/erickfis/NOAA-Storm-Database}

\section{Objective}\label{objective}

The goal of this study is to answer the questions:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Across the United States, which types of events were the most harmful
  with respect to population health ever recorded in a single
  occurrence?
\item
  Which types of events caused most harm to population health along all
  those years?
\item
  Which types of events had the greatest economic consequences in a
  single occurrence?
\item
  Which types of events had the greatest economic consequences along all
  those years?
\item
  Which were the places that were subject to the greatest losses, both
  in terms of human health and economic losses.
\end{enumerate}

\section{Methods}\label{methods}

To answer each one of those questions, we did a very simple
\textbf{descriptive analysis} of data.

We used R tools to filter, sort and combine data, so we could get the
total sum of fatalities, injuries and economic losses.

\section{Data Processing}\label{data-processing}

In order to answer our questions, the original database needed to be
treated from its raw form to a more useful format.

The necessary transformations were:

\begin{itemize}
\tightlist
\item
  sanitized var names
\item
  evaluated duration of events, however they are not useful
\item
  evaluated damages values according to multipliers provided
\item
  sanitized and grouped similar events: strong snow, heavy snow and
  light snow all became just ``snow''
\item
  sanitized county names
\end{itemize}

This database has 48875 observations. Each observation corresponds to an
event occurrence.

To determine the most harmful events to human health, we checked the
variables related to human health, which are ``fatalities'' and
``injuries''.

To determine the most harmful events to economy, we checked the
variables related to economic measures, from ``propdmg'' through
``cropdmgexp''.

Also, in order to analyse various occurrences of the same event, we
measured the duration of the event, its magnitude and where the event
occurred (state and county name).

This is a really big database whose data has been being registered by a
lot of different people since 1950. Thus, as expected, there are
variations on how people registered events.

For example, the string ``snow'' was used to register a lot of events.
They are the same type of event, but count as different:

This is why we decided to filter those events: we grouped them by its
common strings.

\section{Human health: the most harmfull
events}\label{human-health-the-most-harmfull-events}

We have determined what events did more harm to human health.

There were occurrences that caused zero fatalities but a lot of
injuries. The inverse is also true, so we did a separate analysis to
fatal and non-fatal events.

\subsection{Fatal Occurrences}\label{fatal-occurrences}

\subsubsection{Most fatal in a single
occurrence}\label{most-fatal-in-a-single-occurrence}

Most fatal in a single occurrence

In order to determine what were the most fatal events in a single
occurrence, we need to see how fatalities are distributed along the
occurrences.

Looking at this distribution, we can infer that the vast majority of
those occurrences were not fatal at all: \textbf{99.3\% occurrences
didn't caused any fatalities.}

On the other hand, fatal occurrences had to have at least 1 fatality.

Now, among the fatal occurrences, we are interested in the ones whose
fatalities are beyond the confidence interval, ie. above 99\% of the
most common values.

Looking at this distribution, we can infer that \textbf{99.8\% of the
fatal occurrences caused up to 21.058 fattalities}.

\begin{figure}[htbp]
\centering
\includegraphics{readme_files/figure-latex/fatal-distr-4-1.pdf}
\caption{Population distribution for fatalities / occurrences}
\end{figure}

In this study, we looked on the 1\% deadliest occurrences.

\begin{longtable}[]{@{}rllllr@{}}
\caption{Worst fatal occurrences, mean = 1.49 and median =
1}\tabularnewline
\toprule
rank & event & day & state & county & fatalities\tabularnewline
\midrule
\endfirsthead
\toprule
rank & event & day & state & county & fatalities\tabularnewline
\midrule
\endhead
1 & storm & 2001-06-05 & texas & harris & 22\tabularnewline
\bottomrule
\end{longtable}

\begin{figure}[htbp]
\centering
\includegraphics{readme_files/figure-latex/fatal-plot-single-1.pdf}
\caption{Worst fatal occurrences}
\end{figure}

The single most fatal event was a \textbf{storm, that occurred in texas,
harris, on 2001-06-05, killing 22 people.}

However, if we compare this single awful event to the mean of fatalities
caused, we see that this is very unlikely to happen.

\subsubsection{Most fatal in all time}\label{most-fatal-in-all-time}

Most fatal in all time

Notice that are several occurrences of the same type of event along the
time.

Therefore, in order to know which is the worst type of event along all
the years, we summed up the fatalities caused by each one of occurrences
of this events.

Notice that we are interested only in the worst of them, ie, the ones
which are above the mean.

\begin{longtable}[]{@{}rlr@{}}
\caption{Total fatalities by event, mean = 29.31 and median =
12.5}\tabularnewline
\toprule
rank & event & total\tabularnewline
\midrule
\endfirsthead
\toprule
rank & event & total\tabularnewline
\midrule
\endhead
1 & heat & 166\tabularnewline
2 & flood & 52\tabularnewline
3 & rip current & 49\tabularnewline
4 & lightning & 44\tabularnewline
5 & tornado & 40\tabularnewline
6 & wind & 36\tabularnewline
\bottomrule
\end{longtable}

\begin{figure}[htbp]
\centering
\includegraphics{readme_files/figure-latex/fatal-plot-alltime-1.pdf}
\caption{Total fatalities by event}
\end{figure}

The most fatal event along the time is the \textbf{heat. It has killed
166 people until now.}

\subsubsection{Least fatal events}\label{least-fatal-events}

Just for curiosity, these are the less fatal among the fatal events:

\begin{longtable}[]{@{}rlr@{}}
\caption{Least fatal events}\tabularnewline
\toprule
rank & event & total\tabularnewline
\midrule
\endfirsthead
\toprule
rank & event & total\tabularnewline
\midrule
\endhead
16 & hurricane & 1\tabularnewline
15 & snow & 2\tabularnewline
14 & rain & 3\tabularnewline
13 & blizzard & 4\tabularnewline
12 & fire & 5\tabularnewline
11 & surf & 6\tabularnewline
10 & fog & 7\tabularnewline
9 & winter & 7\tabularnewline
8 & avalanche & 18\tabularnewline
7 & storm & 29\tabularnewline
\bottomrule
\end{longtable}

\subsection{Injuring Occurrences}\label{injuring-occurrences}

\subsubsection{Most injuring in a single
occurrence}\label{most-injuring-in-a-single-occurrence}

Most injuring in a single occurrence

In order to determine what were the most injuring events in a single
occurrence, we need to see how injuries are distributed along the
occurrences.

Looking at this distribution, we can infer that the vast majority of
those occurrences were not injuring at all: \textbf{98.5\% occurrences
didn't caused any injuries}

On the other hand, injuring occurrences had to have at least 1 injury.

Now, among the injuring occurrences, we are interested in the ones whose
harm is beyond the confidence interval, ie. above 99\% of the most
common values.

Looking at this distribution, we can infer that \textbf{99.8\% of the
injuring occurrences caused up to 88.694 injuries}.

\begin{figure}[htbp]
\centering
\includegraphics{readme_files/figure-latex/inj-distribution-1.pdf}
\caption{Population distribution for Injuries / occurrences}
\end{figure}

In this study, we looked on the 1\% most injuring occurrences.

\begin{longtable}[]{@{}rllllr@{}}
\caption{Worst injuring occurrences, mean = 4.01 and median =
2}\tabularnewline
\toprule
rank & event & day & state & county & injuries\tabularnewline
\midrule
\endfirsthead
\toprule
rank & event & day & state & county & injuries\tabularnewline
\midrule
\endhead
1 & heat & 2001-08-06 & michigan & wayne & 107\tabularnewline
\bottomrule
\end{longtable}

\begin{figure}[htbp]
\centering
\includegraphics{readme_files/figure-latex/injuring-single-plot-1.pdf}
\caption{Worst injuring occurrences}
\end{figure}

The single most injuring event was a \textbf{heat, that occurred in
michigan, wayne, on 2001-08-06, injuring 107 people.}

However, if we compare this single awful event to the mean of injuries
caused, we see that this is very unlikely to happen.

\subsubsection{Most injuring in all
time}\label{most-injuring-in-all-time}

Notice that are several occurrences of the same type of event along the
time.

Therefore, in order to know which is the worst type of event along all
the years, we summed up the injuries caused by each one of occurrences
of this events.

Notice that we are interested only in the worst of them, ie, the ones
which are above the mean.

\begin{longtable}[]{@{}rlr@{}}
\caption{Total injuries by event, mean = 143.21 and median =
32}\tabularnewline
\toprule
rank & event & total\tabularnewline
\midrule
\endfirsthead
\toprule
rank & event & total\tabularnewline
\midrule
\endhead
1 & tornado & 743\tabularnewline
2 & heat & 445\tabularnewline
3 & wind & 441\tabularnewline
4 & lightning & 372\tabularnewline
5 & flood & 277\tabularnewline
\bottomrule
\end{longtable}

The most injuring event along the time is the \textbf{tornado. It has
injuried 743 people until now.}

\begin{figure}[htbp]
\centering
\includegraphics{readme_files/figure-latex/injuring-all-plot-1.pdf}
\caption{Total Injuries by event}
\end{figure}

\subsubsection{Least injuring events}\label{least-injuring-events}

Just for curiosity, lets show now what are the less injuring among the
injuring events:

\begin{longtable}[]{@{}rlr@{}}
\caption{Least injuring events}\tabularnewline
\toprule
rank & event & total\tabularnewline
\midrule
\endfirsthead
\toprule
rank & event & total\tabularnewline
\midrule
\endhead
19 & dust devil & 1\tabularnewline
18 & rain & 1\tabularnewline
17 & tide & 1\tabularnewline
16 & other & 4\tabularnewline
15 & blizzard & 5\tabularnewline
14 & avalanche & 6\tabularnewline
13 & snow & 19\tabularnewline
12 & storm & 19\tabularnewline
11 & surf & 22\tabularnewline
10 & hail & 32\tabularnewline
\bottomrule
\end{longtable}

\section{Economy: the the most harmfull
events}\label{economy-the-the-most-harmfull-events}

We have determined what events did more harm to economy, both in terms
of property and crops damage.

There were events that causes zero property damage but a lot of crop
damage. The inverse is also true, so we did a separate analysis to
property VS crop damaging events.

\subsection{Property losses}\label{property-losses}

\subsubsection{Most Property Damaging event in a single
occurrence}\label{most-property-damaging-event-in-a-single-occurrence}

In order to determine what were the most property damaging events in a
single occurrence, we need to see how damages are distributed along the
occurrences.

Looking at this distribution, we can infer that 99.8\% of the
occurrences caused less than \textbf{\$69,470,000 in losses}.

On the other hand, damaging occurrences had to have damages above zero.

Now, among the damaging occurrences, we are interested in the ones whose
damages are above 99.8\% of the most common values.

Looking at this distribution, we can infer that \textbf{99.8\% of the
damaging occurrences caused up to \$100,000,000 in losses}.

\begin{figure}[htbp]
\centering
\includegraphics{readme_files/figure-latex/crop-distribution-1.pdf}
\caption{Population distribution for losses / occurrences}
\end{figure}

In this study, we looked on the 1\% most harmful occurrences.

\begin{longtable}[]{@{}lrlllll@{}}
\caption{Worst property damaging occurrences, mean = \$942,545 and
median = \$10,000}\tabularnewline
\toprule
& rank & event & day & state & county & value\tabularnewline
\midrule
\endfirsthead
\toprule
& rank & event & day & state & county & value\tabularnewline
\midrule
\endhead
1 & 1 & storm & 2001-06-05 & texas & harris &
\$5,030,000,000\tabularnewline
2 & 2 & hail & 2001-04-10 & missouri & st.louis &
\$400,000,000\tabularnewline
3 & 3 & hail & 2001-04-10 & nebraska & douglas &
\$300,000,000\tabularnewline
4 & 4 & hail & 2001-04-10 & missouri & st.louis &
\$300,000,000\tabularnewline
5 & 5 & hail & 2001-04-30 & nebraska & douglas &
\$200,000,000\tabularnewline
6 & 6 & flood & 2001-04-01 & minnesota & anoka &
\$200,000,000\tabularnewline
7 & 7 & hail & 2001-05-06 & texas & bexar & \$120,000,000\tabularnewline
8 & 8 & flood & 2001-10-11 & arkansas & columbia &
\$120,000,000\tabularnewline
9 & 9 & hail & 2001-06-09 & north.dakota & morton &
\$113,000,000\tabularnewline
10 & 10 & hail & 2001-06-09 & north.dakota & burleigh &
\$113,000,000\tabularnewline
NA & NA & NA & NA & NA & NA & NA\tabularnewline
NA.1 & NA & NA & NA & NA & NA & NA\tabularnewline
NA.2 & NA & NA & NA & NA & NA & NA\tabularnewline
NA.3 & NA & NA & NA & NA & NA & NA\tabularnewline
NA.4 & NA & NA & NA & NA & NA & NA\tabularnewline
NA.5 & NA & NA & NA & NA & NA & NA\tabularnewline
NA.6 & NA & NA & NA & NA & NA & NA\tabularnewline
NA.7 & NA & NA & NA & NA & NA & NA\tabularnewline
NA.8 & NA & NA & NA & NA & NA & NA\tabularnewline
NA.9 & NA & NA & NA & NA & NA & NA\tabularnewline
\bottomrule
\end{longtable}

\begin{figure}[htbp]
\centering
\includegraphics{readme_files/figure-latex/prop-single-plot-1.pdf}
\caption{Worst property damaging occurrences}
\end{figure}

The single most economic damaging event to properties was a
\textbf{storm, that occurred in texas, harris, on 2001-06-05, causing
U\$ \$5,030,000,000 in losses}.

\subsubsection{Most Property Damaging event in all
time}\label{most-property-damaging-event-in-all-time}

Notice that are several occurrences of the same type of event along the
time.

Therefore, in order to know which is the worst type of event along all
the years, we summed up the losses caused by each one of occurrences of
this events.

Notice that we are interested only in the worst of them, ie, the ones
which are above the mean.

\begin{longtable}[]{@{}rll@{}}
\caption{Total property losses by event, mean = \$527,726,193 and median
= \$20,599,000}\tabularnewline
\toprule
rank & event & total\tabularnewline
\midrule
\endfirsthead
\toprule
rank & event & total\tabularnewline
\midrule
\endhead
1 & storm & \$5,195,880,000\tabularnewline
2 & hail & \$2,368,341,440\tabularnewline
3 & flood & \$1,237,204,000\tabularnewline
4 & tornado & \$630,086,900\tabularnewline
\bottomrule
\end{longtable}

\begin{figure}[htbp]
\centering
\includegraphics{readme_files/figure-latex/prop-all-plot-1.pdf}
\caption{Total Property Damages by event}
\end{figure}

The most property damaging event along the time is the \textbf{storm. It
has caused \$5,195,880,000 in losses.}

\subsubsection{Least property damaging
events}\label{least-property-damaging-events}

Just for curiosity, these are the less damaging events:

\begin{longtable}[]{@{}rll@{}}
\caption{Least property damaging events}\tabularnewline
\toprule
rank & event & total\tabularnewline
\midrule
\endfirsthead
\toprule
rank & event & total\tabularnewline
\midrule
\endhead
19 & dust devil & \$3,000\tabularnewline
18 & avalanche & \$44,000\tabularnewline
17 & rip current & \$60,000\tabularnewline
16 & volcanic ash & \$500,000\tabularnewline
15 & surf & \$622,500\tabularnewline
14 & hurricane & \$650,000\tabularnewline
13 & fog & \$1,283,000\tabularnewline
12 & tide & \$1,460,000\tabularnewline
11 & blizzard & \$8,145,000\tabularnewline
10 & winter & \$20,599,000\tabularnewline
\bottomrule
\end{longtable}

\subsection{Crop losses}\label{crop-losses}

\subsubsection{Most Crop Damaging event in a single
occurrence}\label{most-crop-damaging-event-in-a-single-occurrence}

In order to determine what were the most crop damaging events in a
single occurrence, we need to see how damages are distributed along the
occurrences.

On the other hand, damaging occurrences had to have damages above zero.

Now, among the damaging occurrences, we are interested in the ones whose
damages are above 99\% of the most common values.

Looking at this distribution, we can infer that \textbf{99.8\% of the
damaging occurrences caused up to \$130,250,000 in losses.}

\begin{figure}[htbp]
\centering
\includegraphics{readme_files/figure-latex/crop-distr-4-1.pdf}
\caption{Population distribution for losses / occurrences}
\end{figure}

In this study, we looked on the 1\% most harmful occurrences.

\begin{longtable}[]{@{}lrlllll@{}}
\caption{Worst crops damaging occurrences, mean = \$1,301,381 and median
= \$15,000}\tabularnewline
\toprule
& rank & event & day & state & county & value\tabularnewline
\midrule
\endfirsthead
\toprule
& rank & event & day & state & county & value\tabularnewline
\midrule
\endhead
1 & 1 & drought & 2001-12-01 & texas & parmer &
\$420,000,000\tabularnewline
2 & 2 & drought & 2001-07-01 & michigan & wayne &
\$150,000,000\tabularnewline
NA & NA & NA & NA & NA & NA & NA\tabularnewline
NA.1 & NA & NA & NA & NA & NA & NA\tabularnewline
NA.2 & NA & NA & NA & NA & NA & NA\tabularnewline
NA.3 & NA & NA & NA & NA & NA & NA\tabularnewline
NA.4 & NA & NA & NA & NA & NA & NA\tabularnewline
NA.5 & NA & NA & NA & NA & NA & NA\tabularnewline
NA.6 & NA & NA & NA & NA & NA & NA\tabularnewline
NA.7 & NA & NA & NA & NA & NA & NA\tabularnewline
NA.8 & NA & NA & NA & NA & NA & NA\tabularnewline
NA.9 & NA & NA & NA & NA & NA & NA\tabularnewline
NA.10 & NA & NA & NA & NA & NA & NA\tabularnewline
NA.11 & NA & NA & NA & NA & NA & NA\tabularnewline
NA.12 & NA & NA & NA & NA & NA & NA\tabularnewline
NA.13 & NA & NA & NA & NA & NA & NA\tabularnewline
NA.14 & NA & NA & NA & NA & NA & NA\tabularnewline
NA.15 & NA & NA & NA & NA & NA & NA\tabularnewline
NA.16 & NA & NA & NA & NA & NA & NA\tabularnewline
NA.17 & NA & NA & NA & NA & NA & NA\tabularnewline
\bottomrule
\end{longtable}

\begin{figure}[htbp]
\centering
\includegraphics{readme_files/figure-latex/crop-single-plot-1.pdf}
\caption{Worst crops damaging occurrences}
\end{figure}

The single most economic damaging event to crops was a \textbf{drought,
that occurred in texas, parmer, on 2001-12-01, causing U\$ \$420,000,000
in losses.}

\subsubsection{Most Crop Damaging event in all
time}\label{most-crop-damaging-event-in-all-time}

Notice that are several occurrences of the same type of event along the
time.

Therefore, in order to know which is the worst type of event along all
the years, we summed up the losses caused by each one of occurrences of
this events.

Notice that we are interested only in the worst of them, ie, the ones
which are above the mean.

\begin{longtable}[]{@{}rll@{}}
\caption{Total crops losses by event, mean = \$165,157,100 and median =
\$21,501,000}\tabularnewline
\toprule
rank & event & total\tabularnewline
\midrule
\endfirsthead
\toprule
rank & event & total\tabularnewline
\midrule
\endhead
1 & drought & \$1,273,860,000\tabularnewline
2 & hail & \$270,386,300\tabularnewline
\bottomrule
\end{longtable}

\begin{figure}[htbp]
\centering
\includegraphics{readme_files/figure-latex/crop-all-plot-1.pdf}
\caption{Total Crop Damages by event}
\end{figure}

The most crop damaging event along the time is the \textbf{drought. It
has caused \$1,273,860,000 in losses.}

\subsubsection{Least crops damaging
events}\label{least-crops-damaging-events}

Just for curiosity, lets show now what are the less damaging among the
events:

\begin{longtable}[]{@{}rll@{}}
\caption{Least crops damaging events}\tabularnewline
\toprule
rank & event & total\tabularnewline
\midrule
\endfirsthead
\toprule
rank & event & total\tabularnewline
\midrule
\endhead
11 & winter & \$60,000\tabularnewline
10 & hurricane & \$450,000\tabularnewline
9 & lightning & \$2,007,800\tabularnewline
8 & storm & \$2,200,000\tabularnewline
7 & tornado & \$7,410,500\tabularnewline
6 & rain & \$21,501,000\tabularnewline
5 & flood & \$43,042,500\tabularnewline
4 & cold & \$47,850,000\tabularnewline
3 & wind & \$147,960,000\tabularnewline
2 & hail & \$270,386,300\tabularnewline
\bottomrule
\end{longtable}

\section{Most aflicted locations}\label{most-aflicted-locations}

We have determined what locations had the worst outcome from those
events, both in terms of human health and economic losses.

Unfortunatelly, these has been the worst counties for living in:

\subsection{Worst fatality count}\label{worst-fatality-count}

\begin{longtable}[]{@{}rllrrll@{}}
\caption{Total fatalities by county}\tabularnewline
\toprule
rank & state & county & fatalities & injuries & prop.dmg &
crop.dmg\tabularnewline
\midrule
\endfirsthead
\toprule
rank & state & county & fatalities & injuries & prop.dmg &
crop.dmg\tabularnewline
\midrule
\endhead
1 & texas & harris & 42 & 0 & \$5,079,324,000 & \$0\tabularnewline
2 & illinois & cook & 37 & 9 & \$37,640,000 & \$0\tabularnewline
3 & pennsylvania & philadelphia & 25 & 0 & \$0 & \$0\tabularnewline
4 & florida & escambia & 8 & 5 & \$515,000 & \$0\tabularnewline
5 & guam & guam & 8 & 11 & \$475,000 & \$0\tabularnewline
6 & missouri & st.louis. & 8 & 127 & \$0 & \$0\tabularnewline
7 & missouri & st.louis & 7 & 83 & \$850,385,000 & \$0\tabularnewline
8 & mississippi & pontotoc & 6 & 43 & \$28,045,850 & \$0\tabularnewline
9 & oklahoma & oklahoma & 6 & 3 & \$2,652,000 & \$0\tabularnewline
10 & puerto.rico & northeast & 6 & 0 & \$5,325,000 &
\$1,000,000\tabularnewline
\bottomrule
\end{longtable}

The county with the biggest fatality count is \textbf{harris, in texas,
with 42 people killed.}

\subsection{Worst injuries count}\label{worst-injuries-count}

\begin{longtable}[]{@{}rllrrll@{}}
\caption{Total injuries by county}\tabularnewline
\toprule
rank & state & county & fatalities & injuries & prop.dmg &
crop.dmg\tabularnewline
\midrule
\endfirsthead
\toprule
rank & state & county & fatalities & injuries & prop.dmg &
crop.dmg\tabularnewline
\midrule
\endhead
1 & missouri & st.louis. & 8 & 127 & \$0 & \$0\tabularnewline
2 & michigan & wayne & 0 & 107 & \$95,000 & \$150,000,000\tabularnewline
3 & california & san.diego.mountains & 0 & 106 & \$0 &
\$0\tabularnewline
4 & missouri & st.louis & 7 & 83 & \$850,385,000 & \$0\tabularnewline
5 & michigan & oakland & 1 & 80 & \$1,298,000 & \$0\tabularnewline
6 & texas & travis & 2 & 70 & \$3,065,000 & \$100,000\tabularnewline
7 & maryland & prince.george's & 2 & 58 & \$100,294,000 &
\$0\tabularnewline
8 & south.carolina & horry & 2 & 49 & \$9,133,000 &
\$50,000\tabularnewline
9 & mississippi & pontotoc & 6 & 43 & \$28,045,850 & \$0\tabularnewline
10 & mississippi & bolivar & 0 & 36 & \$8,283,000 & \$0\tabularnewline
\bottomrule
\end{longtable}

The county with the biggest injuries count is \textbf{st.louis., in
missouri, with 127 people injuried.}

\subsection{Worst property losses}\label{worst-property-losses}

\begin{longtable}[]{@{}rllrrll@{}}
\caption{Total property losses by county}\tabularnewline
\toprule
rank & state & county & fatalities & injuries & prop.dmg &
crop.dmg\tabularnewline
\midrule
\endfirsthead
\toprule
rank & state & county & fatalities & injuries & prop.dmg &
crop.dmg\tabularnewline
\midrule
\endhead
1 & texas & harris & 42 & 0 & \$5,079,324,000 & \$0\tabularnewline
2 & missouri & st.louis & 7 & 83 & \$850,385,000 & \$0\tabularnewline
3 & nebraska & douglas & 1 & 1 & \$501,177,000 & \$0\tabularnewline
4 & missouri & st.charles & 1 & 0 & \$205,250,000 & \$0\tabularnewline
5 & minnesota & anoka & 4 & 1 & \$200,100,000 & \$0\tabularnewline
6 & texas & bexar & 0 & 16 & \$120,410,000 & \$30,020,000\tabularnewline
7 & arkansas & columbia & 0 & 0 & \$120,017,000 & \$0\tabularnewline
8 & north.dakota & morton & 0 & 0 & \$113,200,000 & \$0\tabularnewline
9 & north.dakota & burleigh & 0 & 0 & \$113,050,000 & \$0\tabularnewline
10 & texas & lubbock & 0 & 1 & \$101,018,000 &
\$15,635,000\tabularnewline
\bottomrule
\end{longtable}

The county with the biggest property losses is \textbf{harris, in texas,
with \$5,079,324,000 in losses.}

\subsection{Worst crops losses}\label{worst-crops-losses}

\begin{longtable}[]{@{}rllrrll@{}}
\caption{Total crops losses by county}\tabularnewline
\toprule
rank & state & county & fatalities & injuries & prop.dmg &
crop.dmg\tabularnewline
\midrule
\endfirsthead
\toprule
rank & state & county & fatalities & injuries & prop.dmg &
crop.dmg\tabularnewline
\midrule
\endhead
1 & texas & parmer & 0 & 0 & \$413,000 & \$420,035,000\tabularnewline
2 & michigan & wayne & 0 & 107 & \$95,000 & \$150,000,000\tabularnewline
3 & florida & inland.palm.beach & 0 & 0 & \$0 &
\$106,000,000\tabularnewline
4 & washington & yakima & 0 & 2 & \$395,000 &
\$70,000,000\tabularnewline
5 & texas & hockley & 0 & 0 & \$830,000 & \$36,820,000\tabularnewline
6 & florida & inland.collier & 0 & 0 & \$0 & \$34,030,000\tabularnewline
7 & california & ecentralsj & 0 & 10 & \$20,000 &
\$30,800,000\tabularnewline
8 & texas & bexar & 0 & 16 & \$120,410,000 & \$30,020,000\tabularnewline
9 & north.dakota & traill & 0 & 0 & \$1,904,500 &
\$30,000,000\tabularnewline
10 & florida & inland.dade & 0 & 0 & \$0 & \$25,000,000\tabularnewline
\bottomrule
\end{longtable}

The county with the biggest croperty losses is \textbf{parmer, in texas,
with \$420,035,000 in losses.}

\section{Results}\label{results}

\subsection{Population Health}\label{population-health}

\begin{figure}[htbp]
\centering
\includegraphics{readme_files/figure-latex/health-plot-1.pdf}
\caption{Population Health: fatalities and injuries}
\end{figure}

The single most fatal event was a \textbf{storm, that occurred in texas,
harris, on 2001-06-05, killing 22 people.}

The most fatal event along the time is the \textbf{heat. It has killed
166 people until now.}

The single most injuring event was a \textbf{heat, that occurred in
michigan, wayne, on 2001-08-06, injuring 107 people.}

The most injuring event along the time is the \textbf{tornado. It has
injuried 743 people until now.}

\subsection{Economic Damages}\label{economic-damages}

\begin{figure}[htbp]
\centering
\includegraphics{readme_files/figure-latex/economic-plot-1.pdf}
\caption{Economic Damages: property and crops}
\end{figure}

The single most economic damaging event to properties was a
\textbf{storm, that occurred in texas, harris, on 2001-06-05, causing
U\$ \$5,030,000,000 in losses}.

The most property damaging event along the time is the \textbf{storm. It
has caused \$5,195,880,000 in losses.}

The single most economic damaging event to crops was a \textbf{drought,
that occurred in texas, parmer, on 2001-12-01, causing U\$ \$420,000,000
in losses}.

The most crop damaging event along the time is the \textbf{drought. It
has caused \$1,273,860,000 in losses.}

\subsection{Most aflicted locations}\label{most-aflicted-locations-1}

The county with the biggest fatality count is \textbf{harris, in texas,
with 42 people killed.}

The county with the biggest injuries count is \textbf{st.louis., in
missouri, with 127 people injuried.}

The county with the biggest property losses is \textbf{harris, in texas,
with \$5,079,324,000 in losses.}

The county with the biggest croperty losses is \textbf{parmer, in texas,
with \$420,035,000 in losses.}

\subsection{Distribution of data}\label{distribution-of-data}

\includegraphics{readme_files/figure-latex/distribution-1.pdf}
\includegraphics{readme_files/figure-latex/distribution-2.pdf}


\end{document}
