<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />


<meta name="author" content="erickfis" />


<title>NOAA Storm Database - worst cases</title>

<script src="readme_files/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="readme_files/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="readme_files/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="readme_files/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="readme_files/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="readme_files/navigation-1.1/tabsets.js"></script>
<link href="readme_files/highlightjs-1.1/default.css" rel="stylesheet" />
<script src="readme_files/highlightjs-1.1/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs && document.readyState && document.readyState === "complete") {
   window.setTimeout(function() {
      hljs.initHighlighting();
   }, 0);
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>



<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->






<div class="fluid-row" id="header">



<h1 class="title toc-ignore">NOAA Storm Database - worst cases</h1>
<h4 class="author"><em>erickfis</em></h4>
<h4 class="date"><em>2017 abril, 29</em></h4>

</div>

<div id="TOC">
<ul>
<li><a href="#objective"><span class="toc-section-number">1</span> Objective</a></li>
<li><a href="#data-processing"><span class="toc-section-number">2</span> Data Processing</a></li>
<li><a href="#human-health-the-most-harmfull-events"><span class="toc-section-number">3</span> Human health: the most harmfull events</a><ul>
<li><a href="#fatal-occurrences"><span class="toc-section-number">3.1</span> Fatal Occurrences</a><ul>
<li><a href="#most-fatal-in-a-single-occurrence"><span class="toc-section-number">3.1.1</span> Most fatal in a single occurrence</a></li>
<li><a href="#most-fatal-in-all-time"><span class="toc-section-number">3.1.2</span> Most fatal in all time</a></li>
</ul></li>
<li><a href="#injuring-occurrences"><span class="toc-section-number">3.2</span> Injuring Occurrences</a><ul>
<li><a href="#most-injuring-in-a-single-occurrence"><span class="toc-section-number">3.2.1</span> Most injuring in a single occurrence</a></li>
<li><a href="#most-injuring-in-all-time"><span class="toc-section-number">3.2.2</span> Most injuring in all time</a></li>
</ul></li>
</ul></li>
<li><a href="#economy-the-the-most-harmfull-events"><span class="toc-section-number">4</span> Economy: the the most harmfull events</a><ul>
<li><a href="#property-losses"><span class="toc-section-number">4.1</span> Property losses</a><ul>
<li><a href="#most-property-damaging-event-in-a-single-occurrence"><span class="toc-section-number">4.1.1</span> Most Property Damaging event in a single occurrence</a></li>
<li><a href="#most-property-damaging-event-in-all-time"><span class="toc-section-number">4.1.2</span> Most Property Damaging event in all time</a></li>
</ul></li>
<li><a href="#crop-losses"><span class="toc-section-number">4.2</span> Crop losses</a><ul>
<li><a href="#most-crop-damaging-event-in-a-single-occurrence"><span class="toc-section-number">4.2.1</span> Most Crop Damaging event in a single occurrence</a></li>
<li><a href="#most-crop-damaging-event-in-all-time"><span class="toc-section-number">4.2.2</span> Most Crop Damaging event in all time</a></li>
</ul></li>
</ul></li>
<li><a href="#most-aflicted-locations"><span class="toc-section-number">5</span> Most aflicted locations</a><ul>
<li><a href="#worst-fatality-count"><span class="toc-section-number">5.1</span> Worst fatality count</a></li>
<li><a href="#worst-injuries-count"><span class="toc-section-number">5.2</span> Worst injuries count</a></li>
<li><a href="#worst-property-losses"><span class="toc-section-number">5.3</span> Worst property losses</a></li>
<li><a href="#worst-crops-losses"><span class="toc-section-number">5.4</span> Worst crops losses</a></li>
</ul></li>
<li><a href="#results"><span class="toc-section-number">6</span> Results</a><ul>
<li><a href="#population-health"><span class="toc-section-number">6.1</span> Population Health</a></li>
<li><a href="#economic-damages"><span class="toc-section-number">6.2</span> Economic Damages</a></li>
<li><a href="#most-aflicted-locations-1"><span class="toc-section-number">6.3</span> Most aflicted locations</a></li>
<li><a href="#distribution-of-data"><span class="toc-section-number">6.4</span> Distribution of data</a></li>
</ul></li>
</ul>
</div>

<!-- # NOAA Storm Database - worst cases -->
<p>In this study we have analysed the NOAA Storm Database in order to determine what are the worst natural catastrophic events, both in terms of public health and in economic impact.</p>
<p>The U.S. National Oceanic and Atmospheric Administration’s (NOAA) storm database tracks characteristics of major storms and weather events in the United States, including when and where they occur, as well as estimates of any fatalities, injuries, and property damage.</p>
<p>The database currently contains data from January 1950 to January 2017, as entered by NOAA’s National Weather Service (NWS).</p>
<p>The database can be found on:</p>
<p><a href="https://www.ncdc.noaa.gov/stormevents/ftp.jsp" class="uri">https://www.ncdc.noaa.gov/stormevents/ftp.jsp</a></p>
<p>RPubs version, with fewer plots, for Coursera: <a href="http://rpubs.com/erickfis/noaa" class="uri">http://rpubs.com/erickfis/noaa</a></p>
<div id="objective" class="section level1">
<h1><span class="header-section-number">1</span> Objective</h1>
<p>The goal of this study is to answer the questions:</p>
<ol style="list-style-type: decimal">
<li><p>Across the United States, which types of events were the most harmful with respect to population health ever recorded in a single occurrence?</p></li>
<li><p>Which types of events caused most harm to population health along all those years?</p></li>
<li><p>Which types of events had the greatest economic consequences in a single occurrence?</p></li>
<li><p>Which types of events had the greatest economic consequences along all those years?</p></li>
<li><p>Which were the places that were subject to the greatest losses, both in terms of human health and economic losses.</p></li>
</ol>
</div>
<div id="data-processing" class="section level1">
<h1><span class="header-section-number">2</span> Data Processing</h1>
<p>Data Processing</p>
<p>This code loads the original data and them choose which variables are useful to answer our questions:</p>
<pre class="r"><code>library(scales)
library(stringr)
library(data.table)
library(chron)
library(dplyr)
library(lubridate)
library(ggplot2)
library(rmarkdown)
library(RColorBrewer)
library(gridExtra)
library(grid)</code></pre>
<p>Reading original database:</p>
<pre class="r"><code>#fileUrl &lt;- &quot;https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2&quot;

#download.file(fileUrl, &quot;StormData.bz2&quot;, method = &quot;curl&quot;)

#Full data
dados &lt;- fread(sprintf(&quot;bzcat %s | tr -d &#39;\\000&#39;&quot;, &quot;StormData.bz2&quot;), na.strings = &quot;&quot;)</code></pre>
<pre><code>## 
Read 19.6% of 967216 rows
Read 40.3% of 967216 rows
Read 55.8% of 967216 rows
Read 77.5% of 967216 rows
Read 84.8% of 967216 rows
Read 902297 rows and 37 (of 37) columns from 0.523 GB file in 00:00:07</code></pre>
<pre class="r"><code>dados &lt;-tbl_df(dados)

# this do a sample data base, with 50000 obs, used for speeding up initial works:
# linhas &lt;- nrow(dados)
# linhas &lt;- sample(linhas,50000)
# dataS &lt;- dados[linhas,]
# write.csv(dataS, &quot;StormData&quot;)

# dados &lt;- fread(sprintf(&quot;bzcat %s | tr -d &#39;\\000&#39;&quot;, &quot;StormData.bz2&quot;))
# dados &lt;-tbl_df(dados)
# dados &lt;- select(dados, -1)



# treating var names
names(dados) &lt;- gsub(&quot;_&quot;, &quot;.&quot;, tolower(names(dados)))
names(dados)   </code></pre>
<pre><code>##  [1] &quot;state..&quot;    &quot;bgn.date&quot;   &quot;bgn.time&quot;   &quot;time.zone&quot;  &quot;county&quot;    
##  [6] &quot;countyname&quot; &quot;state&quot;      &quot;evtype&quot;     &quot;bgn.range&quot;  &quot;bgn.azi&quot;   
## [11] &quot;bgn.locati&quot; &quot;end.date&quot;   &quot;end.time&quot;   &quot;county.end&quot; &quot;countyendn&quot;
## [16] &quot;end.range&quot;  &quot;end.azi&quot;    &quot;end.locati&quot; &quot;length&quot;     &quot;width&quot;     
## [21] &quot;f&quot;          &quot;mag&quot;        &quot;fatalities&quot; &quot;injuries&quot;   &quot;propdmg&quot;   
## [26] &quot;propdmgexp&quot; &quot;cropdmg&quot;    &quot;cropdmgexp&quot; &quot;wfo&quot;        &quot;stateoffic&quot;
## [31] &quot;zonenames&quot;  &quot;latitude&quot;   &quot;longitude&quot;  &quot;latitude.e&quot; &quot;longitude.&quot;
## [36] &quot;remarks&quot;    &quot;refnum&quot;</code></pre>
<p>This database has 902297 observations. Each observation corresponds to an event occurrence.</p>
<p>To determine the most harmful events to human health, we will check the variables related to human health, which are “fatalities” and “injuries”.</p>
<p>To determine the most harmful events to economy, we will check the variables related to economic measures, from “propdmg” through “cropdmgexp”.</p>
<p>Also, in order to analyse various occurrences of the same event, we will measure the duration of the event, its magnitude and where the event occurred (state and county name).</p>
<pre class="r"><code># select desired vars
harm.df &lt;- dados %&gt;% select(evtype, mag, state, countyname, bgn.date, end.date, 23:28)

# treat vars
harm.df &lt;- harm.df %&gt;% 
        mutate(bgn.date = mdy_hms(bgn.date), end.date = mdy_hms(end.date),  
               day = as.Date(bgn.date, &quot;%m/%d/%Y&quot;), 
               duration = -as.period(interval(end.date, bgn.date)),
               event = tolower(as.character(evtype)),
               countyname =strtrim(countyname,9)) %&gt;%
        select(event, 2, day, duration, 3:4, 7:12)

# fixing exp for economic data
harm.df$propdmgexp[which(harm.df$propdmgexp==&quot;K&quot;)] &lt;- as.character(3)
harm.df$propdmgexp[which(harm.df$propdmgexp==&quot;m&quot;)] &lt;- as.character(6)
harm.df$propdmgexp[which(harm.df$propdmgexp==&quot;M&quot;)] &lt;- as.character(6)
harm.df$propdmgexp[which(harm.df$propdmgexp==&quot;B&quot;)] &lt;- as.character(9)
harm.df$propdmgexp &lt;- as.numeric(harm.df$propdmgexp)

harm.df$cropdmgexp[which(harm.df$cropdmgexp==&quot;K&quot;)] &lt;- as.character(3)
harm.df$cropdmgexp[which(harm.df$cropdmgexp==&quot;m&quot;)] &lt;- as.character(6)
harm.df$cropdmgexp[which(harm.df$cropdmgexp==&quot;M&quot;)] &lt;- as.character(6)
harm.df$cropdmgexp[which(harm.df$cropdmgexp==&quot;B&quot;)] &lt;- as.character(9)
harm.df$cropdmgexp &lt;- as.numeric(harm.df$cropdmgexp)

harm.df &lt;- mutate(harm.df, prop.ev = propdmg*10^propdmgexp,
                crop.ev = cropdmg*10^cropdmgexp)</code></pre>
<p>This is a really big database which data has been being registered by a lot of different people since 1950. Thus, as expected, there are variations on how people registered events.</p>
<p>For exemple, the string “snow” was used to register a lot of events. They are the same type of event, but count as different:</p>
<pre class="r"><code>eventos &lt;- grep(&quot;snow&quot;, harm.df$event, value = TRUE)
eventos &lt;- sort(unique(eventos))
length(eventos)</code></pre>
<pre><code>## [1] 118</code></pre>
<pre class="r"><code>eventos[1:10]</code></pre>
<pre><code>##  [1] &quot;accumulated snowfall&quot;           &quot;blizzard and heavy snow&quot;       
##  [3] &quot;blizzard/heavy snow&quot;            &quot;blowing snow&quot;                  
##  [5] &quot;blowing snow &amp; extreme wind ch&quot; &quot;blowing snow- extreme wind chi&quot;
##  [7] &quot;blowing snow/extreme wind chil&quot; &quot;cold and snow&quot;                 
##  [9] &quot;drifting snow&quot;                  &quot;early snow&quot;</code></pre>
<p>This is why we decided to filter those events: we grouped them by its commom strings.</p>
<pre class="r"><code># treating event types

eventos &lt;- harm.df$event
# first, need to see what are the event types
contagem &lt;- sort(table(eventos))

# them we create this list of terms
 
lista.search &lt;- c(
&quot;dry&quot;,        
&quot;fog&quot;,        
&quot;wind&quot;,
&quot;winter&quot;,
&quot;slide&quot;,
&quot;snow&quot;,
&quot;flood&quot;,
&quot;fld&quot;,
&quot;cold|freez&quot;,
&quot;hurricane&quot;,
&quot;tornado&quot;,
&quot;rain|precip&quot;,
&quot;hail&quot;,
&quot;heat|warm&quot;,
&quot;tide&quot;,
&quot;storm&quot;,
&quot;record&quot;,
&quot;blizzard&quot;,
&quot;fire&quot;,
&quot;funnel&quot;,
&quot;surf&quot;)

lista.replace &lt;- c(
&quot;drought&quot;,
&quot;fog&quot;,        
&quot;wind&quot;,
&quot;winter&quot;,
&quot;slide&quot;,
&quot;snow&quot;,
&quot;flood&quot;,
&quot;flood&quot;,
&quot;cold&quot;,
&quot;hurricane&quot;,
&quot;tornado&quot;,
&quot;rain&quot;,
&quot;hail&quot;,
&quot;heat&quot;,
&quot;tide&quot;,
&quot;storm&quot;,
&quot;record temperature&quot;,
&quot;blizzard&quot;,
&quot;fire&quot;,
&quot;funnel&quot;,
&quot;surf&quot;)


for (i in 1:length(lista.search)) {
        eventos[grepl(lista.search[i], eventos)] &lt;- lista.replace[i]
        
}

# lets group the events whose count is &lt; 5 and call it &quot;other&quot;
contagem &lt;- sort(table(eventos))
outros &lt;- names(contagem[contagem&lt;5])
eventos[eventos %in% outros] &lt;- &quot;other&quot;
# sort(table(eventos))

# returning treated events
harm.df$event &lt;- toupper(eventos)</code></pre>
<pre class="r"><code># Treating County Names
cidades &lt;- toupper(harm.df$countyname)
cidades &lt;- str_trim(cidades)

cidades &lt;- gsub(&quot;_| |-&quot;, &quot;.&quot;, cidades)

cidades[grep(&quot;\\.\\.$&quot;, cidades)] &lt;- gsub(&quot;\\.\\.&quot;, &quot;&quot;,
                                cidades[grep(&quot;\\.\\.$&quot;, cidades)]
                                        )

cidades &lt;- sapply(strsplit(cidades, split=&quot;&gt;&quot;, fixed=TRUE), function(x) (x[1]))
cidades &lt;- sapply(strsplit(cidades, split=&quot;(&quot;, fixed=TRUE), function(x) (x[1]))
cidades &lt;- sapply(strsplit(cidades, split=&quot;,&quot;, fixed=TRUE), function(x) (x[1]))

harm.df$countyname &lt;- cidades

rm(dados) # house cleanning</code></pre>
</div>
<div id="human-health-the-most-harmfull-events" class="section level1">
<h1><span class="header-section-number">3</span> Human health: the most harmfull events</h1>
<p>We have determined what events did more harm to human health.</p>
<p>There were occurrences that caused zero fatalities but a lot of injuries. The inverse is also true, so we did a separate analysis to fatal and non-fatal events.</p>
<div id="fatal-occurrences" class="section level2">
<h2><span class="header-section-number">3.1</span> Fatal Occurrences</h2>
<div id="most-fatal-in-a-single-occurrence" class="section level3">
<h3><span class="header-section-number">3.1.1</span> Most fatal in a single occurrence</h3>
<p>Most fatal in a single occurrence</p>
<p>In order to determine what were the most fatal events in a single occurrence, we need to see how fatalities are distributed along the occurrences.</p>
<pre class="r"><code># subset original data
fatal.df &lt;- harm.df %&gt;% 
                filter(!is.na(fatalities)) %&gt;%
                select(1:7)

  
# quantiles
qt &lt;- quantile(fatal.df$fatalities, probs=seq(.9,1,0.001))

# distribution plot

plt.distr.fatal0 &lt;- ggplot(fatal.df, aes(fatalities))

plt.distr.fatal0 &lt;- plt.distr.fatal0 + geom_density(aes(y=..density..)) + xlim(0,.5) + 
        labs(title=&quot;All events&quot;) +
        theme(plot.title = element_text(hjust = 0.5))

# display only the qts next to fatal events
qt[(length(qt)-(length(qt[qt&gt;=1])+1)): length(qt)]</code></pre>
<pre><code>##  99.1%  99.2%  99.3%  99.4%  99.5%  99.6%  99.7%  99.8%  99.9% 100.0% 
##      0      0      1      1      1      1      1      2      3    583</code></pre>
<p>Looking at this distribution, we can infer that the vast majority of those occurrences were not fatal at all: <strong>99.2% occurrences didn’t caused any fatalities.</strong></p>
<p>On the other hand, fatal occurrences had to have at least 1 fatality.</p>
<p>Now, among the fatal occurrences, we are interested in the ones whose fatalities are beyond the confidence interval, ie. above 99% of the most common values.</p>
<pre class="r"><code># subset for fatal events
fatal.df &lt;- filter(fatal.df, fatalities &gt; 0) %&gt;%
                arrange(desc(fatalities)) %&gt;%
                mutate(mean = mean(fatalities), 
                median = median(fatalities),
                rank = seq_len(length(event)))


# quantiles, same as 
# poisson.test(mean, conf.level = 0.95)

qt &lt;- quantile(fatal.df$fatalities, probs=seq(.999,1,0.005))
qt</code></pre>
<pre><code>##  99.9% 
## 74.027</code></pre>
<p>Looking at this distribution, we can infer that <strong>99.8% of the fatal occurrences caused up to 74.027 fattalities</strong>.</p>
<p>Distribution plots</p>
<pre class="r"><code># distribution plot
 
plt.distr.fatal1 &lt;- ggplot(fatal.df, aes(fatalities))

plt.distr.fatal1 &lt;- plt.distr.fatal1 + geom_density(aes(y=..density..)) + 
        xlim(0,(qt[1]/10)) + 
        labs(title=&quot;Fatal events&quot;) +
        theme(plot.title = element_text(hjust = 0.5))</code></pre>
<pre class="r"><code>grid.arrange(plt.distr.fatal0, plt.distr.fatal1, nrow=1, ncol=2, 
             bottom=&quot;Population distribution&quot;)
grid.rect(gp=gpar(fill=NA))</code></pre>
<p><img src="readme_files/figure-html/fatal-distr-4-1.png" width="672" /></p>
<p>In this study, we looked on the 1% deadliest occurrences.</p>
<pre class="r"><code># subset for 99% CI
fatal95.df &lt;- fatal.df %&gt;% filter(fatalities&gt;qt[1])
                
# create color pallete for all events
colourCount.fatal.single = length(unique(fatal95.df$event))
getPalette = colorRampPalette(brewer.pal(colourCount.fatal.single, &quot;Set1&quot;))

# print a table
kable(fatal95.df[, c(10,1:9)])</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">rank</th>
<th align="left">event</th>
<th align="right">mag</th>
<th align="left">day</th>
<th align="right">duration</th>
<th align="left">state</th>
<th align="left">countyname</th>
<th align="right">fatalities</th>
<th align="right">mean</th>
<th align="right">median</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="left">HEAT</td>
<td align="right">0</td>
<td align="left">1995-07-12</td>
<td align="right">0S</td>
<td align="left">IL</td>
<td align="left">ILZ003</td>
<td align="right">583</td>
<td align="right">2.171638</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="left">TORNADO</td>
<td align="right">0</td>
<td align="left">2011-05-22</td>
<td align="right">0S</td>
<td align="left">MO</td>
<td align="left">JASPER</td>
<td align="right">158</td>
<td align="right">2.171638</td>
<td align="right">1</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="left">TORNADO</td>
<td align="right">0</td>
<td align="left">1953-06-08</td>
<td align="right">NA</td>
<td align="left">MI</td>
<td align="left">GENESEE</td>
<td align="right">116</td>
<td align="right">2.171638</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="left">TORNADO</td>
<td align="right">0</td>
<td align="left">1953-05-11</td>
<td align="right">NA</td>
<td align="left">TX</td>
<td align="left">MCLENNAN</td>
<td align="right">114</td>
<td align="right">2.171638</td>
<td align="right">1</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="left">HEAT</td>
<td align="right">0</td>
<td align="left">1999-07-28</td>
<td align="right">0S</td>
<td align="left">IL</td>
<td align="left">ILZ005</td>
<td align="right">99</td>
<td align="right">2.171638</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="right">6</td>
<td align="left">TORNADO</td>
<td align="right">0</td>
<td align="left">1953-06-09</td>
<td align="right">NA</td>
<td align="left">MA</td>
<td align="left">WORCESTER</td>
<td align="right">90</td>
<td align="right">2.171638</td>
<td align="right">1</td>
</tr>
<tr class="odd">
<td align="right">7</td>
<td align="left">TORNADO</td>
<td align="right">0</td>
<td align="left">1955-05-25</td>
<td align="right">NA</td>
<td align="left">KS</td>
<td align="left">COWLEY</td>
<td align="right">75</td>
<td align="right">2.171638</td>
<td align="right">1</td>
</tr>
</tbody>
</table>
<pre class="r"><code># prepare text for inline R
worst.fatal.single.ev &lt;- fatal95.df$event[1]
worst.fatal.single.st &lt;- fatal95.df$state[1]
worst.fatal.single.ct &lt;- fatal95.df$countyname[1]
worst.fatal.single.dt &lt;- fatal95.df$day[1]
worst.fatal.single.kill &lt;- fatal95.df$fatalities[1]</code></pre>
<pre class="r"><code># the plot
plt.fatal.single &lt;- ggplot(fatal95.df, aes(day, fatalities, colour=event))

plt.fatal.single &lt;- plt.fatal.single + geom_point() +
        geom_text(aes(label=ifelse(rank &lt;= 3,
                 paste0(as.character(day), &quot;: &quot;, fatalities, &quot; killed&quot;) ,&quot;&quot;),
                hjust=-.03,vjust=0.5)) +

        # geom_hline(aes(yintercept = mean), linetype=2) +
        # geom_hline(aes(yintercept = median), linetype=3) +
        labs(title=&quot;Most Fatal&quot;,
                    y=&quot;&quot;, x=&quot;&quot;) +
    
        expand_limits(x=as.Date(&#39;2017-01-01&#39;))+ #ok
        scale_colour_manual(values = getPalette(colourCount.fatal.single))+                
        theme(legend.title=element_blank()) +
        theme(legend.position=&quot;bottom&quot;) +
        guides(fill=guide_legend(nrow=5, byrow=TRUE)) +
        theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
        theme(plot.title = element_text(hjust = 0.5))                 

plt.fatal.single + labs(title=&quot;Most fatal Occurrence&quot;,
                    y=&quot;Fatalities&quot;, x=&quot;&quot;)</code></pre>
<p><img src="readme_files/figure-html/fatal-plot-single-1.png" width="672" /></p>
<p>The single most fatal event was a <strong>HEAT, that occurred in IL, ILZ003, on 1995-07-12, killing 583 people.</strong></p>
<p>However, if we compare this single awful event to the mean of fatalities caused, we see that this is very unlikely to happen.</p>
</div>
<div id="most-fatal-in-all-time" class="section level3">
<h3><span class="header-section-number">3.1.2</span> Most fatal in all time</h3>
<p>Most fatal in all time</p>
<p>Notice that are several occurrences of the same type of event along the time.</p>
<p>Therefore, in order to know which is the worst type of event along all the years, we summed up the fatalities caused by each one of occurrences of this events.</p>
<p>Notice that we are interested only in the worst of them, ie, the ones which are above the mean.</p>
<pre class="r"><code># totals per event
fatal.all.df &lt;- fatal.df %&gt;% group_by(event) %&gt;%
        summarise(total = sum(fatalities)) %&gt;% arrange(desc(total)) %&gt;% 
        mutate(mean = mean(total), median = median(total),
               rank = seq_len(length(event))) %&gt;%
        filter(total &gt; mean(total))

# create color pallete for all events
colourCount.fatal.all = length(unique(fatal.all.df$event))
getPalette = colorRampPalette(brewer.pal(colourCount.fatal.all, &quot;Set1&quot;))

# prepare text for inline R
worst.fatal.all.ev &lt;- fatal.all.df$event[1]
worst.fatal.all.kill &lt;- fatal.all.df$total[1]

# a table
kable(fatal.all.df[,c(5,1:4)])</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">rank</th>
<th align="left">event</th>
<th align="right">total</th>
<th align="right">mean</th>
<th align="right">median</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="left">TORNADO</td>
<td align="right">5636</td>
<td align="right">398.5526</td>
<td align="right">38.5</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="left">HEAT</td>
<td align="right">3149</td>
<td align="right">398.5526</td>
<td align="right">38.5</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="left">FLOOD</td>
<td align="right">1553</td>
<td align="right">398.5526</td>
<td align="right">38.5</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="left">WIND</td>
<td align="right">1451</td>
<td align="right">398.5526</td>
<td align="right">38.5</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="left">LIGHTNING</td>
<td align="right">816</td>
<td align="right">398.5526</td>
<td align="right">38.5</td>
</tr>
</tbody>
</table>
<pre class="r"><code># the plot
plt.fatal.all &lt;- ggplot(data=fatal.all.df, aes(event, total, fill=event))

plt.fatal.all &lt;- plt.fatal.all + geom_bar(stat=&quot;identity&quot;) +
        geom_text(aes(label=ifelse(total==max(total),
                paste0(event, &quot;: &quot;, max(total), &quot; killed&quot;),&#39;&#39;)),
                hjust=0,vjust=2) +
        geom_hline(aes(yintercept = mean), linetype=1) +
        # geom_hline(aes(yintercept = median), linetype=2) +
        labs(title=&quot;All time&quot;, y=&quot;&quot;,
             x=&quot;&quot;) + 
                
        theme(legend.position=&quot;none&quot;) +        
        scale_colour_manual(values = getPalette(colourCount.fatal.all))+                
        theme(legend.title=element_blank()) +
        theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
        theme(plot.title = element_text(hjust = 0.5))                 

plt.fatal.all + labs(title=&quot;Most fatal type of event - all time&quot;,
                    y=&quot;Fatalities&quot;, x=&quot;&quot;)                </code></pre>
<p><img src="readme_files/figure-html/fatal-plot-alltime-1.png" width="672" /></p>
<p>The most fatal event along the time is the <strong>TORNADO. It has killed 5636 people until now.</strong></p>
<p>Just for curiosity, these are the less fatal among the fatal events:</p>
<pre class="r"><code># sort for less dangerous, had to subset again due to previous filtering
fatal.all.df &lt;- fatal.df %&gt;% group_by(event) %&gt;%
        summarise(total = sum(fatalities)) %&gt;% arrange(total) %&gt;% 
        mutate(mean = mean(total), median = median(total),
               rank = seq(length(event),1, by=-1))

# a table
kable(fatal.all.df[1:10,c(5,1:2)])</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">rank</th>
<th align="left">event</th>
<th align="right">total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">38</td>
<td align="left">BLACK ICE</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="right">37</td>
<td align="left">FROST</td>
<td align="right">1</td>
</tr>
<tr class="odd">
<td align="right">36</td>
<td align="left">HIGH SWELLS</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="right">35</td>
<td align="left">WINTRY MIX</td>
<td align="right">1</td>
</tr>
<tr class="odd">
<td align="right">34</td>
<td align="left">DUST DEVIL</td>
<td align="right">2</td>
</tr>
<tr class="even">
<td align="right">33</td>
<td align="left">SLEET</td>
<td align="right">2</td>
</tr>
<tr class="odd">
<td align="right">32</td>
<td align="left">HIGH WATER</td>
<td align="right">3</td>
</tr>
<tr class="even">
<td align="right">31</td>
<td align="left">WATERSPOUT</td>
<td align="right">3</td>
</tr>
<tr class="odd">
<td align="right">30</td>
<td align="left">HIGH SEAS</td>
<td align="right">5</td>
</tr>
<tr class="even">
<td align="right">29</td>
<td align="left">ICY ROADS</td>
<td align="right">5</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="injuring-occurrences" class="section level2">
<h2><span class="header-section-number">3.2</span> Injuring Occurrences</h2>
<div id="most-injuring-in-a-single-occurrence" class="section level3">
<h3><span class="header-section-number">3.2.1</span> Most injuring in a single occurrence</h3>
<p>Most injuring in a single occurrence</p>
<p>In order to determine what were the most injuring events in a single occurrence, we need to see how injuries are distributed along the occurrences.</p>
<pre class="r"><code>rm(fatal.df,fatal.all.df, fatal95.df, qt) # cleannig house


injuring.df &lt;- harm.df %&gt;% filter(!is.na(injuries)) %&gt;%
                select(1:6,8)

# quantiles
qt &lt;- quantile(injuring.df$injuries, probs=seq(.975,1,0.002))

# distribution plot
plt.distr.inj0 &lt;- ggplot(injuring.df, aes(injuries))

plt.distr.inj0 &lt;- plt.distr.inj0 + geom_density(aes(y=..density..)) + xlim(0,0.5) + 
        labs(title=&quot;All events&quot;) +
        theme(plot.title = element_text(hjust = 0.5))


# display only the qts next to injuring events
qt[(length(qt)-(length(qt[qt&gt;=1])+1)): length(qt)]</code></pre>
<pre><code>## 97.7% 97.9% 98.1% 98.3% 98.5% 98.7% 98.9% 99.1% 99.3% 99.5% 99.7% 99.9% 
##     0     0     1     1     1     1     1     2     3     4     8    25</code></pre>
<p>Looking at this distribution, we can infer that the vast majority of those occurrences were not injuring at all: <strong>97.9% occurrences didn’t caused any injuries</strong></p>
<p>On the other hand, injuring occurrences had to have at least 1 injury.</p>
<p>Now, among the injuring occurrences, we are interested in the ones whose harm is beyond the confidence interval, ie. above 99% of the most common values.</p>
<pre class="r"><code># subset for harm events
injuring.df &lt;- injuring.df %&gt;% filter(injuries &gt; 0) %&gt;%
                arrange(desc(injuries)) %&gt;%
                mutate(mean = mean(injuries), 
                median = median(injuries),
                rank = seq_len(length(event)))

# quantiles, same as 
# poisson.test(mean, conf.level = 0.95)

qt &lt;- quantile(injuring.df$injuries, probs=seq(.999,1,0.005))
qt</code></pre>
<pre><code>## 99.9% 
##   500</code></pre>
<p>Looking at this distribution, we can infer that <strong>99.8% of the injuring occurrences caused up to 500 injuries</strong>.</p>
<p>Distribution plots</p>
<pre class="r"><code># distribution plot
plt.distr.inj1 &lt;- ggplot(injuring.df, aes(injuries))

plt.distr.inj1 &lt;- plt.distr.inj1 + geom_density(aes(y=..density..)) + xlim(0,(qt[1]/20)) + 
        labs(title=&quot;Injuring events&quot;) +
        theme(plot.title = element_text(hjust = 0.5))       </code></pre>
<pre class="r"><code>grid.arrange(plt.distr.inj0, plt.distr.inj1,
             nrow=1, ncol=2, 
             bottom=&quot;Population distribution&quot;)
grid.rect(gp=gpar(fill=NA))</code></pre>
<p><img src="readme_files/figure-html/inj-distribution-1.png" width="672" /></p>
<p>In this study, we looked on the 1% most injuring occurrences.</p>
<pre class="r"><code># subset for 99% CI
injuring95.df &lt;- filter(injuring.df, injuries&gt;qt[1])

# create color pallete for all events
colourCount.inj.single = length(unique(injuring95.df$event))
getPalette = colorRampPalette(brewer.pal(colourCount.inj.single, &quot;Set1&quot;))

# print a table
kable(injuring95.df[,c(10,1:9)])</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">rank</th>
<th align="left">event</th>
<th align="right">mag</th>
<th align="left">day</th>
<th align="right">duration</th>
<th align="left">state</th>
<th align="left">countyname</th>
<th align="right">injuries</th>
<th align="right">mean</th>
<th align="right">median</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="left">TORNADO</td>
<td align="right">0</td>
<td align="left">1979-04-10</td>
<td align="right">NA</td>
<td align="left">TX</td>
<td align="left">WICHITA</td>
<td align="right">1700</td>
<td align="right">7.982731</td>
<td align="right">2</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="left">STORM</td>
<td align="right">0</td>
<td align="left">1994-02-08</td>
<td align="right">0S</td>
<td align="left">OH</td>
<td align="left">OHZ42</td>
<td align="right">1568</td>
<td align="right">7.982731</td>
<td align="right">2</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="left">TORNADO</td>
<td align="right">0</td>
<td align="left">1953-06-09</td>
<td align="right">NA</td>
<td align="left">MA</td>
<td align="left">WORCESTER</td>
<td align="right">1228</td>
<td align="right">7.982731</td>
<td align="right">2</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="left">TORNADO</td>
<td align="right">0</td>
<td align="left">1974-04-03</td>
<td align="right">NA</td>
<td align="left">OH</td>
<td align="left">GREENE</td>
<td align="right">1150</td>
<td align="right">7.982731</td>
<td align="right">2</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="left">TORNADO</td>
<td align="right">0</td>
<td align="left">2011-05-22</td>
<td align="right">0S</td>
<td align="left">MO</td>
<td align="left">JASPER</td>
<td align="right">1150</td>
<td align="right">7.982731</td>
<td align="right">2</td>
</tr>
<tr class="even">
<td align="right">6</td>
<td align="left">FLOOD</td>
<td align="right">0</td>
<td align="left">1998-10-17</td>
<td align="right">0S</td>
<td align="left">TX</td>
<td align="left">COMAL</td>
<td align="right">800</td>
<td align="right">7.982731</td>
<td align="right">2</td>
</tr>
<tr class="odd">
<td align="right">7</td>
<td align="left">TORNADO</td>
<td align="right">0</td>
<td align="left">2011-04-27</td>
<td align="right">0S</td>
<td align="left">AL</td>
<td align="left">TUSCALOOS</td>
<td align="right">800</td>
<td align="right">7.982731</td>
<td align="right">2</td>
</tr>
<tr class="even">
<td align="right">8</td>
<td align="left">TORNADO</td>
<td align="right">0</td>
<td align="left">1953-06-08</td>
<td align="right">NA</td>
<td align="left">MI</td>
<td align="left">GENESEE</td>
<td align="right">785</td>
<td align="right">7.982731</td>
<td align="right">2</td>
</tr>
<tr class="odd">
<td align="right">9</td>
<td align="left">HURRICANE</td>
<td align="right">0</td>
<td align="left">2004-08-13</td>
<td align="right">0S</td>
<td align="left">FL</td>
<td align="left">FLZ055</td>
<td align="right">780</td>
<td align="right">7.982731</td>
<td align="right">2</td>
</tr>
<tr class="even">
<td align="right">10</td>
<td align="left">FLOOD</td>
<td align="right">0</td>
<td align="left">1998-10-17</td>
<td align="right">0S</td>
<td align="left">TX</td>
<td align="left">TXZ206</td>
<td align="right">750</td>
<td align="right">7.982731</td>
<td align="right">2</td>
</tr>
<tr class="odd">
<td align="right">11</td>
<td align="left">TORNADO</td>
<td align="right">0</td>
<td align="left">2011-04-27</td>
<td align="right">0S</td>
<td align="left">AL</td>
<td align="left">JEFFERSON</td>
<td align="right">700</td>
<td align="right">7.982731</td>
<td align="right">2</td>
</tr>
<tr class="even">
<td align="right">12</td>
<td align="left">FLOOD</td>
<td align="right">0</td>
<td align="left">1998-10-17</td>
<td align="right">0S</td>
<td align="left">TX</td>
<td align="left">BEXAR</td>
<td align="right">600</td>
<td align="right">7.982731</td>
<td align="right">2</td>
</tr>
<tr class="odd">
<td align="right">13</td>
<td align="left">TORNADO</td>
<td align="right">0</td>
<td align="left">1953-05-11</td>
<td align="right">NA</td>
<td align="left">TX</td>
<td align="left">MCLENNAN</td>
<td align="right">597</td>
<td align="right">7.982731</td>
<td align="right">2</td>
</tr>
<tr class="even">
<td align="right">14</td>
<td align="left">TORNADO</td>
<td align="right">0</td>
<td align="left">1965-04-11</td>
<td align="right">NA</td>
<td align="left">IN</td>
<td align="left">HOWARD</td>
<td align="right">560</td>
<td align="right">7.982731</td>
<td align="right">2</td>
</tr>
<tr class="odd">
<td align="right">15</td>
<td align="left">FLOOD</td>
<td align="right">0</td>
<td align="left">1998-10-17</td>
<td align="right">0S</td>
<td align="left">TX</td>
<td align="left">TXZ205</td>
<td align="right">550</td>
<td align="right">7.982731</td>
<td align="right">2</td>
</tr>
<tr class="even">
<td align="right">16</td>
<td align="left">HEAT</td>
<td align="right">0</td>
<td align="left">2007-08-04</td>
<td align="right">0S</td>
<td align="left">MO</td>
<td align="left">MOZ061</td>
<td align="right">519</td>
<td align="right">7.982731</td>
<td align="right">2</td>
</tr>
<tr class="odd">
<td align="right">17</td>
<td align="left">TORNADO</td>
<td align="right">0</td>
<td align="left">1966-03-03</td>
<td align="right">NA</td>
<td align="left">MS</td>
<td align="left">HINDS</td>
<td align="right">504</td>
<td align="right">7.982731</td>
<td align="right">2</td>
</tr>
</tbody>
</table>
<pre class="r"><code># prepare text for inline R
worst.injuring.single.ev &lt;- injuring95.df$event[1]
worst.injuring.single.st &lt;- injuring95.df$state[1]
worst.injuring.single.ct &lt;- injuring95.df$countyname[1]
worst.injuring.single.dt &lt;- injuring95.df$day[1]
worst.injuring.single.inj &lt;- injuring95.df$injuries[1]</code></pre>
<pre class="r"><code># the plot
plt.inj.single &lt;- ggplot(injuring95.df, aes(day, injuries, colour=event))

plt.inj.single &lt;- plt.inj.single + geom_point() +
        geom_text(aes(label=ifelse(rank &lt;= 3,
                 paste0(as.character(day), &quot;: &quot;, injuries, &quot; injuried&quot;) ,&quot;&quot;),
                hjust=-.03,vjust=0.5)) +

        # geom_hline(aes(yintercept = mean), linetype=2) +
        # geom_hline(aes(yintercept = median), linetype=3) +
        labs(title=&quot;Most Injuring&quot;,
                    y=&quot;&quot;, x=&quot;&quot;) +
                
        expand_limits(x=as.Date(&#39;2017-01-01&#39;))+ #ok
        scale_colour_manual(values = getPalette(colourCount.inj.single))+                
        theme(legend.title=element_blank()) +
        theme(legend.position=&quot;bottom&quot;) +
        guides(fill=guide_legend(nrow=5, byrow=TRUE)) +
        theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
        theme(plot.title = element_text(hjust = 0.5)) 

plt.inj.single + labs(title=&quot;Most Injuring Occurrence&quot;,
                    y=&quot;Injuries&quot;, x=&quot;&quot;) </code></pre>
<p><img src="readme_files/figure-html/injuring-single-plot-1.png" width="672" /></p>
<pre class="r"><code>        # scale_y_continuous(expand = c(0, 0)) +
        # geom_hline(aes(yintercept = mean), linetype=2) +
        # geom_hline(aes(yintercept = median), linetype=3)</code></pre>
<p>The single most injuring event was a <strong>TORNADO, that occurred in TX, WICHITA, on 1979-04-10, injuring 1700 people.</strong></p>
<p>However, if we compare this single awful event to the mean of injuries caused, we see that this is very unlikely to happen.</p>
</div>
<div id="most-injuring-in-all-time" class="section level3">
<h3><span class="header-section-number">3.2.2</span> Most injuring in all time</h3>
<p>Most injuring in all time</p>
<p>Notice that are several occurrences of the same type of event along the time.</p>
<p>Therefore, in order to know which is the worst type of event along all the years, we summed up the injuries caused by each one of occurrences of this events.</p>
<p>Notice that we are interested only in the worst of them, ie, the ones which are above the mean.</p>
<pre class="r"><code># totals per event
injuring.all.df &lt;- injuring.df %&gt;% group_by(event) %&gt;% 
        summarise(total = sum(injuries)) %&gt;%
        arrange(desc(total)) %&gt;% 
        mutate(mean = mean(total), median = median(total),
               rank = seq_len(length(event)))  %&gt;%
        filter(total &gt;= mean(total))

# create color pallete for all events
colourCount.inj.all = length(unique(injuring.all.df$event))
getPalette = colorRampPalette(brewer.pal(colourCount.inj.all, &quot;Set1&quot;))

# prepare text for inline R
worst.injuring.all.ev &lt;- injuring.all.df$event[1]
worst.injuring.all.inj &lt;- injuring.all.df$total[1]

# a table
kable(injuring.all.df[,c(5,1:4)])</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">rank</th>
<th align="left">event</th>
<th align="right">total</th>
<th align="right">mean</th>
<th align="right">median</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="left">TORNADO</td>
<td align="right">91407</td>
<td align="right">4015.086</td>
<td align="right">232</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="left">WIND</td>
<td align="right">11497</td>
<td align="right">4015.086</td>
<td align="right">232</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="left">HEAT</td>
<td align="right">9243</td>
<td align="right">4015.086</td>
<td align="right">232</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="left">FLOOD</td>
<td align="right">8683</td>
<td align="right">4015.086</td>
<td align="right">232</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="left">LIGHTNING</td>
<td align="right">5230</td>
<td align="right">4015.086</td>
<td align="right">232</td>
</tr>
</tbody>
</table>
<p>The most injuring event along the time is the <strong>TORNADO. It has injuried 91407 people until now.</strong></p>
<pre class="r"><code># the plot
plt.inj.all &lt;- ggplot(data=injuring.all.df, aes(event, total, fill=event))

plt.inj.all &lt;- plt.inj.all + geom_bar(stat=&quot;identity&quot;) +
        geom_text(aes(label=ifelse(total==max(total),
                paste0(event, &quot;: &quot;, max(total), &quot; injuried&quot;),&#39;&#39;)),
                hjust=0,vjust=2) +
        geom_hline(aes(yintercept = mean), linetype=1) +
        # geom_hline(aes(yintercept = median), linetype=2) +
        labs(title=&quot;All time&quot;, 
             y=&quot;&quot;, x=&quot;&quot;) + 
                
        theme(legend.position=&quot;none&quot;) +        
        scale_colour_manual(values = getPalette(colourCount.inj.all))+                
        theme(legend.title=element_blank()) +
        theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
        theme(plot.title = element_text(hjust = 0.5))                 
                

plt.inj.all  + labs(title=&quot;Most Injuring type of event - all time&quot;,
                    y=&quot;Injuries&quot;, x=&quot;&quot;)</code></pre>
<p><img src="readme_files/figure-html/injuring-all-plot-1.png" width="672" /></p>
<p>Just for curiosity, lets show now what are the less injuring among the injuring events:</p>
<pre class="r"><code># sort for less dangerous, had to subset again due to previous filtering
injuring.all.df &lt;- injuring.df %&gt;% group_by(event) %&gt;%
        summarise(total = sum(injuries)) %&gt;% arrange(total) %&gt;% 
        mutate(mean = mean(total), median = median(total),
               rank = seq(length(event),1, by=-1))

# a table
kable(injuring.all.df[1:10,c(5,1:2)])</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">rank</th>
<th align="left">event</th>
<th align="right">total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">35</td>
<td align="left">FROST</td>
<td align="right">3</td>
</tr>
<tr class="even">
<td align="right">34</td>
<td align="left">FUNNEL</td>
<td align="right">3</td>
</tr>
<tr class="odd">
<td align="right">33</td>
<td align="left">TIDE</td>
<td align="right">5</td>
</tr>
<tr class="even">
<td align="right">32</td>
<td align="left">TYPHOON</td>
<td align="right">5</td>
</tr>
<tr class="odd">
<td align="right">31</td>
<td align="left">HIGH SEAS</td>
<td align="right">8</td>
</tr>
<tr class="even">
<td align="right">30</td>
<td align="left">OTHER</td>
<td align="right">21</td>
</tr>
<tr class="odd">
<td align="right">29</td>
<td align="left">BLACK ICE</td>
<td align="right">24</td>
</tr>
<tr class="even">
<td align="right">28</td>
<td align="left">WATERSPOUT</td>
<td align="right">29</td>
</tr>
<tr class="odd">
<td align="right">27</td>
<td align="left">ICY ROADS</td>
<td align="right">31</td>
</tr>
<tr class="even">
<td align="right">26</td>
<td align="left">DROUGHT</td>
<td align="right">33</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div id="economy-the-the-most-harmfull-events" class="section level1">
<h1><span class="header-section-number">4</span> Economy: the the most harmfull events</h1>
<p>We have determined what events did more harm to economy, both in terms of property and crops damage.</p>
<p>There were events that causes zero property damage but a lot of crop damage. The inverse is also true, so we did a separate analysis to property VS crop damaging events.</p>
<div id="property-losses" class="section level2">
<h2><span class="header-section-number">4.1</span> Property losses</h2>
<div id="most-property-damaging-event-in-a-single-occurrence" class="section level3">
<h3><span class="header-section-number">4.1.1</span> Most Property Damaging event in a single occurrence</h3>
<p>Most Property Damaging event in a single occurrence</p>
<p>In order to determine what were the most property damaging events in a single occurrence, we need to see how damages are distributed along the occurrences.</p>
<pre class="r"><code># property damages
rm(injuring.df, injuring.all.df, injuring95.df) # cleannig house

prop.df &lt;- harm.df %&gt;% filter(!is.na(prop.ev)) %&gt;%
                        select(1:6,13)
                

# quantiles
qt &lt;- quantile(prop.df$prop.ev, probs=seq(.999,1,0.002))

# distribution plot
plt.distr.prop0 &lt;- ggplot(prop.df, aes(log(prop.ev)))

plt.distr.prop0 &lt;- plt.distr.prop0 + geom_density(aes(y=..density..)) + #xlim(0,.5) + 
        labs(title=&quot;All events&quot;, x=&quot;log(amount $)&quot;) +
        theme(plot.title = element_text(hjust = 0.5))       


# display only the qts next to harmfull events
qt</code></pre>
<pre><code>##    99.9% 
## 53931800</code></pre>
<p>Looking at this distribution, we can infer that 99.8% of the occurrences caused less than <strong>$53,931,800 in losses</strong>.</p>
<p>On the other hand, damaging occurrences had to have damages above zero.</p>
<p>Now, among the damaging occurrences, we are interested in the ones whose damages are above 99.8% of the most common values.</p>
<pre class="r"><code># subset for harm events
prop.df &lt;- prop.df %&gt;% filter(prop.ev &gt; 0) %&gt;%
                arrange(desc(prop.ev)) %&gt;%
                mutate(value = dollar(prop.ev),
                        media.raw = mean(prop.ev), 
                        mediana.raw = median(prop.ev),
                        mean = dollar(media.raw),
                        median = dollar(mediana.raw),
                        rank = seq_len(length(event)))
# quantiles, same as 

qt &lt;- quantile(prop.df$prop.ev, probs=seq(.999,1,0.002))
qt</code></pre>
<pre><code>##     99.9% 
## 120000000</code></pre>
<p>Looking at this distribution, we can infer that <strong>99.8% of the damaging occurrences caused up to $120,000,000 in losses</strong>.</p>
<p>Distribution plots</p>
<pre class="r"><code># distribution plot
plt.distr.prop1 &lt;- ggplot(prop.df, aes(log(prop.ev)))

plt.distr.prop1 &lt;- plt.distr.prop1 + geom_density(aes(y=..density..)) + #xlim(0,100) + 
        labs(title=&quot;Damaging events&quot;, x=&quot;log(amount $)&quot;) +
        theme(plot.title = element_text(hjust = 0.5))     </code></pre>
<pre class="r"><code>grid.arrange(plt.distr.prop0, plt.distr.prop1,
             nrow=1, ncol=2, 
             bottom=&quot;Population distribution&quot;)
grid.rect(gp=gpar(fill=NA))</code></pre>
<p><img src="readme_files/figure-html/crop-distribution-1.png" width="672" /></p>
<p>In this study, we looked on the 1% most harmful occurrences.</p>
<pre class="r"><code># subset for 99% CI
prop95.df &lt;- filter(prop.df, prop.ev&gt;qt[1])

# create color pallete for all events
colourCount.prop.single = length(unique(prop95.df$event))
getPalette = colorRampPalette(brewer.pal(colourCount.prop.single, &quot;Set1&quot;))


# print a table
kable(prop95.df[1:20,c(13,1:6,8,11:12)])</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">rank</th>
<th align="left">event</th>
<th align="right">mag</th>
<th align="left">day</th>
<th align="right">duration</th>
<th align="left">state</th>
<th align="left">countyname</th>
<th align="left">value</th>
<th align="left">mean</th>
<th align="left">median</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="left">FLOOD</td>
<td align="right">0</td>
<td align="left">2006-01-01</td>
<td align="right">0S</td>
<td align="left">CA</td>
<td align="left">NAPA</td>
<td align="left">$115,000,000,000</td>
<td align="left">$1,791,099</td>
<td align="left">$10,000</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="left">STORM</td>
<td align="right">0</td>
<td align="left">2005-08-29</td>
<td align="right">0S</td>
<td align="left">LA</td>
<td align="left">LAZ040</td>
<td align="left">$31,300,000,000</td>
<td align="left">$1,791,099</td>
<td align="left">$10,000</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="left">HURRICANE</td>
<td align="right">0</td>
<td align="left">2005-08-28</td>
<td align="right">0S</td>
<td align="left">LA</td>
<td align="left">LAZ034</td>
<td align="left">$16,930,000,000</td>
<td align="left">$1,791,099</td>
<td align="left">$10,000</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="left">STORM</td>
<td align="right">0</td>
<td align="left">2005-08-29</td>
<td align="right">0S</td>
<td align="left">MS</td>
<td align="left">MSZ080</td>
<td align="left">$11,260,000,000</td>
<td align="left">$1,791,099</td>
<td align="left">$10,000</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="left">HURRICANE</td>
<td align="right">0</td>
<td align="left">2005-10-24</td>
<td align="right">0S</td>
<td align="left">FL</td>
<td align="left">FLZ068</td>
<td align="left">$10,000,000,000</td>
<td align="left">$1,791,099</td>
<td align="left">$10,000</td>
</tr>
<tr class="even">
<td align="right">6</td>
<td align="left">HURRICANE</td>
<td align="right">0</td>
<td align="left">2005-08-28</td>
<td align="right">0S</td>
<td align="left">MS</td>
<td align="left">MSZ068</td>
<td align="left">$7,350,000,000</td>
<td align="left">$1,791,099</td>
<td align="left">$10,000</td>
</tr>
<tr class="odd">
<td align="right">7</td>
<td align="left">HURRICANE</td>
<td align="right">0</td>
<td align="left">2005-08-29</td>
<td align="right">0S</td>
<td align="left">MS</td>
<td align="left">MSZ018</td>
<td align="left">$5,880,000,000</td>
<td align="left">$1,791,099</td>
<td align="left">$10,000</td>
</tr>
<tr class="even">
<td align="right">8</td>
<td align="left">HURRICANE</td>
<td align="right">0</td>
<td align="left">2004-08-13</td>
<td align="right">0S</td>
<td align="left">FL</td>
<td align="left">FLZ055</td>
<td align="left">$5,420,000,000</td>
<td align="left">$1,791,099</td>
<td align="left">$10,000</td>
</tr>
<tr class="odd">
<td align="right">9</td>
<td align="left">STORM</td>
<td align="right">0</td>
<td align="left">2001-06-05</td>
<td align="right">0S</td>
<td align="left">TX</td>
<td align="left">TXZ163</td>
<td align="left">$5,150,000,000</td>
<td align="left">$1,791,099</td>
<td align="left">$10,000</td>
</tr>
<tr class="even">
<td align="right">10</td>
<td align="left">WINTER</td>
<td align="right">0</td>
<td align="left">1993-03-12</td>
<td align="right">0S</td>
<td align="left">AL</td>
<td align="left">ALZ001</td>
<td align="left">$5,000,000,000</td>
<td align="left">$1,791,099</td>
<td align="left">$10,000</td>
</tr>
<tr class="odd">
<td align="right">11</td>
<td align="left">FLOOD</td>
<td align="right">0</td>
<td align="left">1993-08-31</td>
<td align="right">NA</td>
<td align="left">IL</td>
<td align="left">ADAMS</td>
<td align="left">$5,000,000,000</td>
<td align="left">$1,791,099</td>
<td align="left">$10,000</td>
</tr>
<tr class="even">
<td align="right">12</td>
<td align="left">HURRICANE</td>
<td align="right">0</td>
<td align="left">2004-09-04</td>
<td align="right">0S</td>
<td align="left">FL</td>
<td align="left">FLZ041</td>
<td align="left">$4,830,000,000</td>
<td align="left">$1,791,099</td>
<td align="left">$10,000</td>
</tr>
<tr class="odd">
<td align="right">13</td>
<td align="left">HURRICANE</td>
<td align="right">0</td>
<td align="left">2004-09-13</td>
<td align="right">0S</td>
<td align="left">FL</td>
<td align="left">FLZ001</td>
<td align="left">$4,000,000,000</td>
<td align="left">$1,791,099</td>
<td align="left">$10,000</td>
</tr>
<tr class="even">
<td align="right">14</td>
<td align="left">HURRICANE</td>
<td align="right">0</td>
<td align="left">2005-09-23</td>
<td align="right">0S</td>
<td align="left">LA</td>
<td align="left">LAZ027</td>
<td align="left">$4,000,000,000</td>
<td align="left">$1,791,099</td>
<td align="left">$10,000</td>
</tr>
<tr class="odd">
<td align="right">15</td>
<td align="left">TIDE</td>
<td align="right">0</td>
<td align="left">2008-09-12</td>
<td align="right">0S</td>
<td align="left">TX</td>
<td align="left">TXZ213</td>
<td align="left">$4,000,000,000</td>
<td align="left">$1,791,099</td>
<td align="left">$10,000</td>
</tr>
<tr class="even">
<td align="right">16</td>
<td align="left">FLOOD</td>
<td align="right">0</td>
<td align="left">1997-04-18</td>
<td align="right">0S</td>
<td align="left">ND</td>
<td align="left">NDZ027</td>
<td align="left">$3,000,000,000</td>
<td align="left">$1,791,099</td>
<td align="left">$10,000</td>
</tr>
<tr class="odd">
<td align="right">17</td>
<td align="left">HURRICANE</td>
<td align="right">0</td>
<td align="left">1999-09-15</td>
<td align="right">0S</td>
<td align="left">NC</td>
<td align="left">NCZ007</td>
<td align="left">$3,000,000,000</td>
<td align="left">$1,791,099</td>
<td align="left">$10,000</td>
</tr>
<tr class="even">
<td align="right">18</td>
<td align="left">TORNADO</td>
<td align="right">0</td>
<td align="left">2011-05-22</td>
<td align="right">0S</td>
<td align="left">MO</td>
<td align="left">JASPER</td>
<td align="left">$2,800,000,000</td>
<td align="left">$1,791,099</td>
<td align="left">$10,000</td>
</tr>
<tr class="odd">
<td align="right">19</td>
<td align="left">RAIN</td>
<td align="right">0</td>
<td align="left">1995-05-08</td>
<td align="right">0S</td>
<td align="left">LA</td>
<td align="left">LAFOURCHE</td>
<td align="left">$2,500,000,000</td>
<td align="left">$1,791,099</td>
<td align="left">$10,000</td>
</tr>
<tr class="even">
<td align="right">20</td>
<td align="left">HURRICANE</td>
<td align="right">0</td>
<td align="left">2004-09-13</td>
<td align="right">0S</td>
<td align="left">AL</td>
<td align="left">ALZ051</td>
<td align="left">$2,500,000,000</td>
<td align="left">$1,791,099</td>
<td align="left">$10,000</td>
</tr>
</tbody>
</table>
<pre class="r"><code># prepare text for inline R
worst.prop.single.ev &lt;- prop95.df$event[1]
worst.prop.single.st &lt;- prop95.df$state[1]
worst.prop.single.ct &lt;- prop95.df$countyname[1]
worst.prop.single.dt &lt;- prop95.df$day[1]
worst.prop.single.value &lt;- prop95.df$value[1]</code></pre>
<pre class="r"><code>plt.prop.single &lt;- ggplot(prop95.df, aes(day, prop.ev, colour=event))

plt.prop.single &lt;- plt.prop.single + geom_point() +
        geom_text(aes(label=ifelse(rank &lt;= 3,
                as.character(day),&quot;&quot;),
                hjust=-.03,vjust=0.5)) +
        # geom_hline(aes(yintercept = media.raw), linetype=2) +
         # geom_hline(aes(yintercept = mediana.raw), linetype=3) +
        labs(title=&quot;Property Dammaging&quot;,
                    y=&quot;&quot;, x=&quot;&quot;) + 
                
        expand_limits(x=as.Date(&#39;2017-01-01&#39;))+ #ok
        scale_y_continuous(labels = dollar)+
        
        scale_colour_manual(values = getPalette(colourCount.prop.single))+                
        theme(legend.title=element_blank()) +
        theme(legend.position=&quot;bottom&quot;) +
        guides(fill=guide_legend(nrow=5, byrow=TRUE)) +
        theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
        theme(plot.title = element_text(hjust = 0.5)) 

plt.prop.single + labs(title=&quot;Most property damaging Occurrence&quot;,
                    y=&quot;Losses&quot;, x=&quot;&quot;)</code></pre>
<p><img src="readme_files/figure-html/prop-single-plot-1.png" width="672" /></p>
<p>The single most economic damaging event to properties was a <strong>FLOOD, that occurred in CA, NAPA, on 2006-01-01, causing U$ $115,000,000,000 in losses</strong>.</p>
</div>
<div id="most-property-damaging-event-in-all-time" class="section level3">
<h3><span class="header-section-number">4.1.2</span> Most Property Damaging event in all time</h3>
<p>Most Property Damaging event in all time</p>
<p>Notice that are several occurrences of the same type of event along the time.</p>
<p>Therefore, in order to know which is the worst type of event along all the years, we summed up the losses caused by each one of occurrences of this events.</p>
<p>Notice that we are interested only in the worst of them, ie, the ones which are above the mean.</p>
<pre class="r"><code># totals per event
prop.all.df &lt;- prop.df %&gt;% group_by(event) %&gt;%
                summarise(total.raw = sum(prop.ev)) %&gt;%
                arrange(desc(total.raw)) %&gt;%
                mutate(media.raw = mean(total.raw), 
                        mediana.raw = median(total.raw),
                        total = dollar(total.raw),
                        mean = dollar(media.raw),
                        median = dollar(mediana.raw),
                        rank = seq_len(length(event))) %&gt;%
                filter(total.raw &gt; mean(total.raw))
                
# create color pallete for all events
colourCount.prop.all = length(unique(prop.all.df$event))
getPalette = colorRampPalette(brewer.pal(colourCount.prop.all, &quot;Set1&quot;))

# prepare text for inline R
worst.prop.all.ev &lt;- prop.all.df$event[1]
worst.prop.total &lt;- prop.all.df$total[1]

# a table
kable(prop.all.df[, c(8,1,5:7)])</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">rank</th>
<th align="left">event</th>
<th align="left">total</th>
<th align="left">mean</th>
<th align="left">median</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="left">FLOOD</td>
<td align="left">$168,258,894,238</td>
<td align="left">$9,309,236,205</td>
<td align="left">$6,537,750</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="left">HURRICANE</td>
<td align="left">$84,656,180,010</td>
<td align="left">$9,309,236,205</td>
<td align="left">$6,537,750</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="left">TORNADO</td>
<td align="left">$57,003,317,814</td>
<td align="left">$9,309,236,205</td>
<td align="left">$6,537,750</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="left">STORM</td>
<td align="left">$56,197,366,960</td>
<td align="left">$9,309,236,205</td>
<td align="left">$6,537,750</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="left">WIND</td>
<td align="left">$17,951,211,793</td>
<td align="left">$9,309,236,205</td>
<td align="left">$6,537,750</td>
</tr>
<tr class="even">
<td align="right">6</td>
<td align="left">HAIL</td>
<td align="left">$15,977,047,956</td>
<td align="left">$9,309,236,205</td>
<td align="left">$6,537,750</td>
</tr>
</tbody>
</table>
<pre class="r"><code>plt.prop.all &lt;- ggplot(data=prop.all.df, aes(event, total.raw, fill=event))

plt.prop.all &lt;- plt.prop.all + geom_bar(stat=&quot;identity&quot;) +
                
        geom_text(aes(label=ifelse(total.raw==max(total.raw),
                paste(event, dollar(max(total.raw)), sep=&quot;: &quot;),&#39;&#39;)),
                hjust=0,vjust=2) +
        geom_hline(aes(yintercept = media.raw), linetype=1) +
        # geom_hline(aes(yintercept = mediana.raw), linetype=2) +
        labs(title=&quot;All time&quot;, y=&quot;&quot;, x=&quot;&quot;) + 
                
        scale_y_continuous(labels = dollar)+
     
        theme(legend.position=&quot;none&quot;) +        
        scale_colour_manual(values = getPalette(colourCount.prop.all))+                
        theme(legend.title=element_blank()) +
        theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
        theme(plot.title = element_text(hjust = 0.5))                 

plt.prop.all + labs(title=&quot;Most property damaging type of event - all time&quot;,
                    y=&quot;Losses&quot;, x=&quot;&quot;)</code></pre>
<p><img src="readme_files/figure-html/prop-all-plot-1.png" width="672" /></p>
<p>The most property damaging event along the time is the <strong>FLOOD. It has caused $168,258,894,238 in losses.</strong></p>
<p>Just for curiosity, these are the less damaging events:</p>
<pre class="r"><code>prop.all.df &lt;- prop.df %&gt;% group_by(event) %&gt;%
                summarise(total.raw = sum(prop.ev)) %&gt;%
                arrange(total.raw) %&gt;%
                mutate(media.raw = mean(total.raw), 
                        mediana.raw = median(total.raw),
                        total = dollar(total.raw),
                        mean = dollar(media.raw),
                        median = dollar(mediana.raw),
                        rank = seq(length(event),1, by=-1))



kable(prop.all.df[1:10, c(8,1,5:7)])</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">rank</th>
<th align="left">event</th>
<th align="left">total</th>
<th align="left">mean</th>
<th align="left">median</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">46</td>
<td align="left">RIP CURRENT</td>
<td align="left">$1,000</td>
<td align="left">$9,309,236,205</td>
<td align="left">$6,537,750</td>
</tr>
<tr class="even">
<td align="right">45</td>
<td align="left">HIGH SWELLS</td>
<td align="left">$5,000</td>
<td align="left">$9,309,236,205</td>
<td align="left">$6,537,750</td>
</tr>
<tr class="odd">
<td align="right">44</td>
<td align="left">URBAN/SMALL STREAM</td>
<td align="left">$5,000</td>
<td align="left">$9,309,236,205</td>
<td align="left">$6,537,750</td>
</tr>
<tr class="even">
<td align="right">43</td>
<td align="left">WINTRY MIX</td>
<td align="left">$12,500</td>
<td align="left">$9,309,236,205</td>
<td align="left">$6,537,750</td>
</tr>
<tr class="odd">
<td align="right">42</td>
<td align="left">FROST</td>
<td align="left">$15,000</td>
<td align="left">$9,309,236,205</td>
<td align="left">$6,537,750</td>
</tr>
<tr class="even">
<td align="right">41</td>
<td align="left">HIGH SEAS</td>
<td align="left">$15,500</td>
<td align="left">$9,309,236,205</td>
<td align="left">$6,537,750</td>
</tr>
<tr class="odd">
<td align="right">40</td>
<td align="left">WET MICROBURST</td>
<td align="left">$35,000</td>
<td align="left">$9,309,236,205</td>
<td align="left">$6,537,750</td>
</tr>
<tr class="even">
<td align="right">39</td>
<td align="left">MICROBURST</td>
<td align="left">$80,000</td>
<td align="left">$9,309,236,205</td>
<td align="left">$6,537,750</td>
</tr>
<tr class="odd">
<td align="right">38</td>
<td align="left">DENSE SMOKE</td>
<td align="left">$100,000</td>
<td align="left">$9,309,236,205</td>
<td align="left">$6,537,750</td>
</tr>
<tr class="even">
<td align="right">37</td>
<td align="left">GUSTNADO</td>
<td align="left">$102,050</td>
<td align="left">$9,309,236,205</td>
<td align="left">$6,537,750</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="crop-losses" class="section level2">
<h2><span class="header-section-number">4.2</span> Crop losses</h2>
<div id="most-crop-damaging-event-in-a-single-occurrence" class="section level3">
<h3><span class="header-section-number">4.2.1</span> Most Crop Damaging event in a single occurrence</h3>
<p>Most Crop Damaging event in a single occurrence</p>
<p>In order to determine what were the most crop damaging events in a single occurrence, we need to see how damages are distributed along the occurrences.</p>
<pre class="r"><code># crop damages
rm(prop.df, prop.all.df, prop95.df) # cleannig house

crop.df &lt;- harm.df %&gt;% filter(!is.na(crop.ev)) %&gt;%
                select(1:6,14) 


# quantiles
qt &lt;- quantile(crop.df$crop.ev, probs=seq(.998,1,0.002))

# distribution plot
plt.distr.crop0 &lt;- ggplot(crop.df, aes(log(crop.ev)))

plt.distr.crop0 &lt;- plt.distr.crop0 + geom_density(aes(y=..density..)) + #xlim(0,.5) + 
        labs(title=&quot;All events&quot;, x=&quot;log(amount $)&quot;) +
        theme(plot.title = element_text(hjust = 0.5))  


# display only the qts next to harmfull events
qt</code></pre>
<pre><code>##      99.8%       100% 
##    7000000 5000000000</code></pre>
<p>Looking at this distribution, we can infer that 99% of the occurrences caused less than <strong>$7,000,000 in losses</strong>.</p>
<p>On the other hand, damaging occurrences had to have damages above zero.</p>
<p>Now, among the damaging occurrences, we are interested in the ones whose damages are above 99% of the most common values.</p>
<pre class="r"><code># subset for harm events
crop.df &lt;- crop.df %&gt;% filter(crop.ev &gt; 0) %&gt;%
                arrange(desc(crop.ev)) %&gt;%
                mutate(value = dollar(crop.ev),
                        media.raw = mean(crop.ev), 
                        mediana.raw = median(crop.ev),
                        mean = dollar(media.raw),
                        median = dollar(mediana.raw),
                        rank = seq_len(length(event)))

# quantiles, same as 
# poisson.test(mean, conf.level = 0.95)

qt &lt;- quantile(crop.df$crop.ev, probs=seq(.999,1,0.005))
qt</code></pre>
<pre><code>##     99.9% 
## 336111520</code></pre>
<p>Looking at this distribution, we can infer that <strong>99.8% of the damaging occurrences caused up to $336,111,520 in losses.</strong></p>
<p>Distribution plots</p>
<pre class="r"><code># distribution plot
plt.distr.crop1 &lt;- ggplot(crop.df, aes(log(crop.ev)))

plt.distr.crop1 &lt;- plt.distr.crop1 + geom_density(aes(y=..density..)) + #xlim(0,qt[1]) + 
        labs(title=&quot;Damaging events&quot;, x=&quot;log(amount $)&quot;) +
        # scale_x_continuous(labels = dollar)+
        # theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
        theme(plot.title = element_text(hjust = 0.5))       </code></pre>
<pre class="r"><code>grid.arrange(plt.distr.crop0, plt.distr.crop1,
             nrow=1, ncol=2, 
             bottom=&quot;Population distribution&quot;)
grid.rect(gp=gpar(fill=NA))</code></pre>
<p><img src="readme_files/figure-html/crop-distr-4-1.png" width="672" /></p>
<p>In this study, we looked on the 1% most harmful occurrences.</p>
<pre class="r"><code># subset for 99% CI
crop95.df &lt;- filter(crop.df, crop.ev&gt;qt[1])

# create color pallete for all events
colourCount.crop.single = length(unique(crop95.df$event))
getPalette = colorRampPalette(brewer.pal(colourCount.crop.single, &quot;Set1&quot;))


# print a table
kable(crop95.df[1:20,c(13,1:6,8,11:12)])</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">rank</th>
<th align="left">event</th>
<th align="right">mag</th>
<th align="left">day</th>
<th align="right">duration</th>
<th align="left">state</th>
<th align="left">countyname</th>
<th align="left">value</th>
<th align="left">mean</th>
<th align="left">median</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="left">FLOOD</td>
<td align="right">0</td>
<td align="left">1993-08-31</td>
<td align="right">NA</td>
<td align="left">IL</td>
<td align="left">ADAMS</td>
<td align="left">$5,000,000,000</td>
<td align="left">$2,224,406</td>
<td align="left">$15,000</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="left">STORM</td>
<td align="right">0</td>
<td align="left">1994-02-09</td>
<td align="right">0S</td>
<td align="left">MS</td>
<td align="left">MSZ001</td>
<td align="left">$5,000,000,000</td>
<td align="left">$2,224,406</td>
<td align="left">$15,000</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="left">HURRICANE</td>
<td align="right">0</td>
<td align="left">2005-08-29</td>
<td align="right">0S</td>
<td align="left">MS</td>
<td align="left">MSZ018</td>
<td align="left">$1,510,000,000</td>
<td align="left">$2,224,406</td>
<td align="left">$15,000</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="left">DROUGHT</td>
<td align="right">0</td>
<td align="left">2006-01-01</td>
<td align="right">0S</td>
<td align="left">TX</td>
<td align="left">TXZ091</td>
<td align="left">$1,000,000,000</td>
<td align="left">$2,224,406</td>
<td align="left">$15,000</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="left">COLD</td>
<td align="right">0</td>
<td align="left">1998-12-20</td>
<td align="right">0S</td>
<td align="left">CA</td>
<td align="left">CAZ020</td>
<td align="left">$596,000,000</td>
<td align="left">$2,224,406</td>
<td align="left">$15,000</td>
</tr>
<tr class="even">
<td align="right">6</td>
<td align="left">DROUGHT</td>
<td align="right">0</td>
<td align="left">2001-08-01</td>
<td align="right">0S</td>
<td align="left">IA</td>
<td align="left">IAZ004</td>
<td align="left">$578,850,000</td>
<td align="left">$2,224,406</td>
<td align="left">$15,000</td>
</tr>
<tr class="odd">
<td align="right">7</td>
<td align="left">DROUGHT</td>
<td align="right">0</td>
<td align="left">2000-11-01</td>
<td align="right">0S</td>
<td align="left">TX</td>
<td align="left">TXZ021</td>
<td align="left">$515,000,000</td>
<td align="left">$2,224,406</td>
<td align="left">$15,000</td>
</tr>
<tr class="even">
<td align="right">8</td>
<td align="left">DROUGHT</td>
<td align="right">0</td>
<td align="left">1995-08-01</td>
<td align="right">0S</td>
<td align="left">IA</td>
<td align="left">IAZ004</td>
<td align="left">$500,000,000</td>
<td align="left">$2,224,406</td>
<td align="left">$15,000</td>
</tr>
<tr class="odd">
<td align="right">9</td>
<td align="left">DROUGHT</td>
<td align="right">0</td>
<td align="left">1998-07-06</td>
<td align="right">0S</td>
<td align="left">OK</td>
<td align="left">OKZ049</td>
<td align="left">$500,000,000</td>
<td align="left">$2,224,406</td>
<td align="left">$15,000</td>
</tr>
<tr class="even">
<td align="right">10</td>
<td align="left">HURRICANE</td>
<td align="right">0</td>
<td align="left">1999-09-15</td>
<td align="right">0S</td>
<td align="left">NC</td>
<td align="left">NCZ007</td>
<td align="left">$500,000,000</td>
<td align="left">$2,224,406</td>
<td align="left">$15,000</td>
</tr>
<tr class="odd">
<td align="right">11</td>
<td align="left">DROUGHT</td>
<td align="right">0</td>
<td align="left">1999-07-01</td>
<td align="right">0S</td>
<td align="left">PA</td>
<td align="left">PAZ006</td>
<td align="left">$500,000,000</td>
<td align="left">$2,224,406</td>
<td align="left">$15,000</td>
</tr>
<tr class="even">
<td align="right">12</td>
<td align="left">FLOOD</td>
<td align="right">0</td>
<td align="left">2000-10-03</td>
<td align="right">0S</td>
<td align="left">FL</td>
<td align="left">FLZ072</td>
<td align="left">$500,000,000</td>
<td align="left">$2,224,406</td>
<td align="left">$15,000</td>
</tr>
<tr class="odd">
<td align="right">13</td>
<td align="left">FLOOD</td>
<td align="right">0</td>
<td align="left">2007-07-01</td>
<td align="right">0S</td>
<td align="left">MO</td>
<td align="left">HENRY</td>
<td align="left">$500,000,000</td>
<td align="left">$2,224,406</td>
<td align="left">$15,000</td>
</tr>
<tr class="even">
<td align="right">14</td>
<td align="left">HEAT</td>
<td align="right">0</td>
<td align="left">2006-07-16</td>
<td align="right">0S</td>
<td align="left">CA</td>
<td align="left">CAZ089</td>
<td align="left">$492,400,000</td>
<td align="left">$2,224,406</td>
<td align="left">$15,000</td>
</tr>
<tr class="odd">
<td align="right">15</td>
<td align="left">DROUGHT</td>
<td align="right">0</td>
<td align="left">2002-12-01</td>
<td align="right">0S</td>
<td align="left">NE</td>
<td align="left">NEZ039</td>
<td align="left">$480,000,000</td>
<td align="left">$2,224,406</td>
<td align="left">$15,000</td>
</tr>
<tr class="even">
<td align="right">16</td>
<td align="left">DROUGHT</td>
<td align="right">0</td>
<td align="left">1998-12-01</td>
<td align="right">0S</td>
<td align="left">TX</td>
<td align="left">TXZ021</td>
<td align="left">$450,000,000</td>
<td align="left">$2,224,406</td>
<td align="left">$15,000</td>
</tr>
<tr class="odd">
<td align="right">17</td>
<td align="left">HURRICANE</td>
<td align="right">0</td>
<td align="left">2005-08-25</td>
<td align="right">0S</td>
<td align="left">FL</td>
<td align="left">FLZ068</td>
<td align="left">$423,000,000</td>
<td align="left">$2,224,406</td>
<td align="left">$15,000</td>
</tr>
<tr class="even">
<td align="right">18</td>
<td align="left">DROUGHT</td>
<td align="right">0</td>
<td align="left">2001-12-01</td>
<td align="right">0S</td>
<td align="left">TX</td>
<td align="left">TXZ021</td>
<td align="left">$420,000,000</td>
<td align="left">$2,224,406</td>
<td align="left">$15,000</td>
</tr>
<tr class="odd">
<td align="right">19</td>
<td align="left">HURRICANE</td>
<td align="right">0</td>
<td align="left">1999-09-14</td>
<td align="right">0S</td>
<td align="left">NC</td>
<td align="left">NCZ029</td>
<td align="left">$413,600,000</td>
<td align="left">$2,224,406</td>
<td align="left">$15,000</td>
</tr>
<tr class="even">
<td align="right">20</td>
<td align="left">HEAT</td>
<td align="right">0</td>
<td align="left">1995-08-20</td>
<td align="right">NA</td>
<td align="left">AL</td>
<td align="left">TALLADEGA</td>
<td align="left">$400,000,000</td>
<td align="left">$2,224,406</td>
<td align="left">$15,000</td>
</tr>
</tbody>
</table>
<pre class="r"><code>worst.crop.single.ev &lt;- crop95.df$event[1]
worst.crop.single.st &lt;- crop95.df$state[1]
worst.crop.single.ct &lt;- crop95.df$countyname[1]
worst.crop.single.dt &lt;- crop95.df$day[1]
worst.crop.single.value &lt;- crop95.df$value[1]</code></pre>
<pre class="r"><code>plt.crop.single &lt;- ggplot(crop95.df, aes(day, crop.ev, colour=event))

plt.crop.single &lt;- plt.crop.single + geom_point() +
        geom_text(aes(label=ifelse(rank &lt;= 3,
                as.character(day),&quot;&quot;),
                hjust=-.03,vjust=0.5)) +
        # geom_hline(aes(yintercept = media.raw), linetype=2) +
        # geom_hline(aes(yintercept = mediana.raw), linetype=3) +
        labs(title=&quot;Crop Dammaging&quot;,
                    y=&quot;&quot;, x=&quot;&quot;) + 
                
        expand_limits(x=as.Date(&#39;2017-01-01&#39;))+ #ok
        scale_y_continuous(labels = dollar)+
        
        scale_colour_manual(values = getPalette(colourCount.crop.single))+                
        theme(legend.title=element_blank()) +
        theme(legend.position=&quot;bottom&quot;) +
        guides(fill=guide_legend(nrow=5, byrow=TRUE)) +
        theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
        theme(plot.title = element_text(hjust = 0.5)) 

plt.crop.single + labs(title=&quot;Most crop damaging Occurrence&quot;,
                    y=&quot;Losses&quot;, x=&quot;&quot;)</code></pre>
<p><img src="readme_files/figure-html/crop-single-plot-1.png" width="672" /></p>
<p>The single most economic damaging event to crops was a <strong>FLOOD, that occurred in IL, ADAMS, on 1993-08-31, causing U$ $5,000,000,000 in losses.</strong></p>
</div>
<div id="most-crop-damaging-event-in-all-time" class="section level3">
<h3><span class="header-section-number">4.2.2</span> Most Crop Damaging event in all time</h3>
<p>Most Crop Damaging event in all time</p>
<p>Notice that are several occurrences of the same type of event along the time.</p>
<p>Therefore, in order to know which is the worst type of event along all the years, we summed up the losses caused by each one of occurrences of this events.</p>
<p>Notice that we are interested only in the worst of them, ie, the ones which are above the mean.</p>
<pre class="r"><code># totals per event
crop.all.df &lt;- crop.df %&gt;% group_by(event) %&gt;%
                summarise(total.raw = sum(crop.ev)) %&gt;%
                arrange(desc(total.raw)) %&gt;%
                mutate(media.raw = mean(total.raw), 
                        mediana.raw = median(total.raw),
                        total = dollar(total.raw),
                        mean = dollar(media.raw),
                        median = dollar(mediana.raw),
                        rank = seq_len(length(event))) %&gt;%
                filter(total.raw &gt; mean(total.raw))
                
# create color pallete for all events
colourCount.crop.all = length(unique(crop.all.df$event))
getPalette = colorRampPalette(brewer.pal(colourCount.crop.all, &quot;Set1&quot;))

# prepare text for inline R
worst.crop.all.ev &lt;- crop.all.df$event[1]
worst.crop.total &lt;- crop.all.df$total[1]

# a table
kable(crop.all.df[, c(8,1,5:7)])</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">rank</th>
<th align="left">event</th>
<th align="left">total</th>
<th align="left">mean</th>
<th align="left">median</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="left">DROUGHT</td>
<td align="left">$13,972,581,000</td>
<td align="left">$2,231,988,917</td>
<td align="left">$296,658,415</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="left">FLOOD</td>
<td align="left">$12,275,737,200</td>
<td align="left">$2,231,988,917</td>
<td align="left">$296,658,415</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="left">STORM</td>
<td align="left">$5,738,319,500</td>
<td align="left">$2,231,988,917</td>
<td align="left">$296,658,415</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="left">HURRICANE</td>
<td align="left">$5,505,292,800</td>
<td align="left">$2,231,988,917</td>
<td align="left">$296,658,415</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="left">COLD</td>
<td align="left">$3,298,176,550</td>
<td align="left">$2,231,988,917</td>
<td align="left">$296,658,415</td>
</tr>
<tr class="even">
<td align="right">6</td>
<td align="left">HAIL</td>
<td align="left">$3,046,470,470</td>
<td align="left">$2,231,988,917</td>
<td align="left">$296,658,415</td>
</tr>
</tbody>
</table>
<pre class="r"><code>plt.crop.all &lt;- ggplot(data=crop.all.df, aes(event, total.raw, fill=event))

plt.crop.all &lt;- plt.crop.all + geom_bar(stat=&quot;identity&quot;) +
                
        geom_text(aes(label=ifelse(total.raw==max(total.raw),
                paste(event, dollar(max(total.raw)), sep=&quot;: &quot;),&#39;&#39;)),
                hjust=0,vjust=2) +
        geom_hline(aes(yintercept = media.raw), linetype=1) +
        # geom_hline(aes(yintercept = mediana.raw), linetype=2) +
        labs(title=&quot;All time&quot;, y=&quot;&quot;, x=&quot;&quot;) + 
                
        scale_y_continuous(labels = dollar)+
     
        theme(legend.position=&quot;none&quot;) +        
        scale_colour_manual(values = getPalette(colourCount.crop.all))+                
        theme(legend.title=element_blank()) +
        theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
        theme(plot.title = element_text(hjust = 0.5))                 

plt.crop.all + labs(title=&quot;Most crops damaging type of event - all time&quot;,
                    y=&quot;Losses&quot;, x=&quot;&quot;)</code></pre>
<p><img src="readme_files/figure-html/crop-all-plot-1.png" width="672" /></p>
<p>The most crop damaging event along the time is the <strong>DROUGHT. It has caused $13,972,581,000 in losses.</strong></p>
<p>Just for curiosity, lets show now what are the less damaging among the events:</p>
<pre class="r"><code>crop.all.df &lt;- crop.df %&gt;% group_by(event) %&gt;%
                summarise(total.raw = sum(crop.ev)) %&gt;%
                arrange(total.raw) %&gt;%
                mutate(media.raw = mean(total.raw), 
                        mediana.raw = median(total.raw),
                        total = dollar(total.raw),
                        mean = dollar(media.raw),
                        median = dollar(mediana.raw),
                        rank = seq(length(event),1, by=-1))



kable(crop.all.df[1:10, c(8,1,5:7)])</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">rank</th>
<th align="left">event</th>
<th align="left">total</th>
<th align="left">mean</th>
<th align="left">median</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">22</td>
<td align="left">GUSTNADO</td>
<td align="left">$1,550</td>
<td align="left">$2,231,988,917</td>
<td align="left">$296,658,415</td>
</tr>
<tr class="even">
<td align="right">21</td>
<td align="left">TSUNAMI</td>
<td align="left">$20,000</td>
<td align="left">$2,231,988,917</td>
<td align="left">$296,658,415</td>
</tr>
<tr class="odd">
<td align="right">20</td>
<td align="left">TYPHOON</td>
<td align="left">$825,000</td>
<td align="left">$2,231,988,917</td>
<td align="left">$296,658,415</td>
</tr>
<tr class="even">
<td align="right">19</td>
<td align="left">TIDE</td>
<td align="left">$850,000</td>
<td align="left">$2,231,988,917</td>
<td align="left">$296,658,415</td>
</tr>
<tr class="odd">
<td align="right">18</td>
<td align="left">LIGHTNING</td>
<td align="left">$12,092,090</td>
<td align="left">$2,231,988,917</td>
<td align="left">$296,658,415</td>
</tr>
<tr class="even">
<td align="right">17</td>
<td align="left">SLIDE</td>
<td align="left">$20,017,000</td>
<td align="left">$2,231,988,917</td>
<td align="left">$296,658,415</td>
</tr>
<tr class="odd">
<td align="right">16</td>
<td align="left">WINTER</td>
<td align="left">$42,444,000</td>
<td align="left">$2,231,988,917</td>
<td align="left">$296,658,415</td>
</tr>
<tr class="even">
<td align="right">15</td>
<td align="left">FROST</td>
<td align="left">$66,000,000</td>
<td align="left">$2,231,988,917</td>
<td align="left">$296,658,415</td>
</tr>
<tr class="odd">
<td align="right">14</td>
<td align="left">BLIZZARD</td>
<td align="left">$112,060,000</td>
<td align="left">$2,231,988,917</td>
<td align="left">$296,658,415</td>
</tr>
<tr class="even">
<td align="right">13</td>
<td align="left">SNOW</td>
<td align="left">$134,663,100</td>
<td align="left">$2,231,988,917</td>
<td align="left">$296,658,415</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div id="most-aflicted-locations" class="section level1">
<h1><span class="header-section-number">5</span> Most aflicted locations</h1>
<p>Most afflicted locations</p>
<p>We have determined what locations had the worst outcome from those events, both in terms of human health and economic losses.</p>
<p>Unfortunatelly, these has been the worst counties for living in:</p>
<pre class="r"><code># subset original data
cities.df &lt;- harm.df %&gt;% 
                filter(!(is.na(countyname) | is.na(state))) %&gt;%
                select(6,5,7:14) %&gt;%
                group_by(state, countyname) %&gt;%
                summarise(fatalities = sum(fatalities, na.rm=TRUE),
                        injuries = sum(injuries, na.rm=TRUE),
                        prop.dmg = sum(prop.ev, na.rm=TRUE),
                        crop.dmg = sum(crop.ev, na.rm=TRUE)
                )</code></pre>
<div id="worst-fatality-count" class="section level2">
<h2><span class="header-section-number">5.1</span> Worst fatality count</h2>
<pre class="r"><code>cities.fatal.df &lt;- arrange(cities.df, desc(fatalities)) %&gt;% ungroup(state, countyname) %&gt;%
      mutate(rank = seq_len(length(fatalities)),
                prop.dmg = dollar(prop.dmg),
                crop.dmg = dollar(crop.dmg)
             )

kable(cities.fatal.df[1:10, c(7,1:6)])</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">rank</th>
<th align="left">state</th>
<th align="left">countyname</th>
<th align="right">fatalities</th>
<th align="right">injuries</th>
<th align="left">prop.dmg</th>
<th align="left">crop.dmg</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="left">IL</td>
<td align="left">ILZ003</td>
<td align="right">605</td>
<td align="right">14</td>
<td align="left">$429,000</td>
<td align="left">$0</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="left">IL</td>
<td align="left">ILZ014</td>
<td align="right">300</td>
<td align="right">22</td>
<td align="left">$2,321,000</td>
<td align="left">$0</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="left">PA</td>
<td align="left">PAZ054</td>
<td align="right">174</td>
<td align="right">295</td>
<td align="left">$124,701,980</td>
<td align="left">$25,000,000</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="left">MO</td>
<td align="left">JASPER</td>
<td align="right">165</td>
<td align="right">1271</td>
<td align="left">$2,858,007,330</td>
<td align="left">$5,500</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="left">MI</td>
<td align="left">GENESEE</td>
<td align="right">121</td>
<td align="right">925</td>
<td align="left">$87,108,750</td>
<td align="left">$5,000,000</td>
</tr>
<tr class="even">
<td align="right">6</td>
<td align="left">TX</td>
<td align="left">MCLENNAN</td>
<td align="right">117</td>
<td align="right">635</td>
<td align="left">$63,071,100</td>
<td align="left">$4,000</td>
</tr>
<tr class="odd">
<td align="right">7</td>
<td align="left">TX</td>
<td align="left">TXZ163</td>
<td align="right">116</td>
<td align="right">3</td>
<td align="left">$6,131,681,000</td>
<td align="left">$270,200,000</td>
</tr>
<tr class="even">
<td align="right">8</td>
<td align="left">IL</td>
<td align="left">ILZ005</td>
<td align="right">114</td>
<td align="right">0</td>
<td align="left">$277,000</td>
<td align="left">$0</td>
</tr>
<tr class="odd">
<td align="right">9</td>
<td align="left">AL</td>
<td align="left">JEFFERSON</td>
<td align="right">110</td>
<td align="right">1576</td>
<td align="left">$2,024,930,600</td>
<td align="left">$2,254,000</td>
</tr>
<tr class="even">
<td align="right">10</td>
<td align="left">PA</td>
<td align="left">PAZ037</td>
<td align="right">107</td>
<td align="right">0</td>
<td align="left">$0</td>
<td align="left">$0</td>
</tr>
</tbody>
</table>
<pre class="r"><code>worst.fatal.city.county &lt;- cities.fatal.df$countyname[1]
worst.fatal.city.st &lt;- cities.fatal.df$state[1]
worst.fatal.city.count &lt;- cities.fatal.df$fatalities[1]</code></pre>
<p>The county with the biggest fatality count is <strong>ILZ003, in IL, with 605 people killed.</strong></p>
</div>
<div id="worst-injuries-count" class="section level2">
<h2><span class="header-section-number">5.2</span> Worst injuries count</h2>
<pre class="r"><code>rm(cities.fatal.df) # house cleanning
cities.inj.df &lt;- arrange(cities.df, desc(injuries)) %&gt;% ungroup(state, countyname) %&gt;%
      mutate(rank = seq_len(length(injuries)),
                prop.dmg = dollar(prop.dmg),
                crop.dmg = dollar(crop.dmg)
             )

kable(cities.inj.df[1:10, c(7,1:6)])</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">rank</th>
<th align="left">state</th>
<th align="left">countyname</th>
<th align="right">fatalities</th>
<th align="right">injuries</th>
<th align="left">prop.dmg</th>
<th align="left">crop.dmg</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="left">TX</td>
<td align="left">WICHITA</td>
<td align="right">51</td>
<td align="right">1852</td>
<td align="left">$310,139,880</td>
<td align="left">$0</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="left">AL</td>
<td align="left">JEFFERSON</td>
<td align="right">110</td>
<td align="right">1576</td>
<td align="left">$2,024,930,600</td>
<td align="left">$2,254,000</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="left">OH</td>
<td align="left">OHZ42</td>
<td align="right">1</td>
<td align="right">1568</td>
<td align="left">$50,000,000</td>
<td align="left">$5,000,000</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="left">MA</td>
<td align="left">WORCESTER</td>
<td align="right">96</td>
<td align="right">1289</td>
<td align="left">$284,569,630</td>
<td align="left">$0</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="left">OH</td>
<td align="left">GREENE</td>
<td align="right">37</td>
<td align="right">1275</td>
<td align="left">$269,935,250</td>
<td align="left">$0</td>
</tr>
<tr class="even">
<td align="right">6</td>
<td align="left">MO</td>
<td align="left">JASPER</td>
<td align="right">165</td>
<td align="right">1271</td>
<td align="left">$2,858,007,330</td>
<td align="left">$5,500</td>
</tr>
<tr class="odd">
<td align="right">7</td>
<td align="left">MO</td>
<td align="left">MOZ061</td>
<td align="right">9</td>
<td align="right">1133</td>
<td align="left">$1,000</td>
<td align="left">$0</td>
</tr>
<tr class="even">
<td align="right">8</td>
<td align="left">AL</td>
<td align="left">TUSCALOOS</td>
<td align="right">60</td>
<td align="right">1103</td>
<td align="left">$1,604,059,750</td>
<td align="left">$725,000</td>
</tr>
<tr class="odd">
<td align="right">9</td>
<td align="left">MO</td>
<td align="left">MOZ009</td>
<td align="right">73</td>
<td align="right">978</td>
<td align="left">$3,225,050</td>
<td align="left">$23,649,200</td>
</tr>
<tr class="even">
<td align="right">10</td>
<td align="left">MI</td>
<td align="left">GENESEE</td>
<td align="right">121</td>
<td align="right">925</td>
<td align="left">$87,108,750</td>
<td align="left">$5,000,000</td>
</tr>
</tbody>
</table>
<pre class="r"><code>worst.inj.city.county &lt;- cities.inj.df$countyname[1]
worst.inj.city.st &lt;- cities.inj.df$state[1]
worst.inj.city.count &lt;- cities.inj.df$injuries[1]</code></pre>
<p>The county with the biggest injuries count is <strong>WICHITA, in TX, with 1852 people injuried.</strong></p>
</div>
<div id="worst-property-losses" class="section level2">
<h2><span class="header-section-number">5.3</span> Worst property losses</h2>
<pre class="r"><code>rm(cities.inj.df) # house cleanning

cities.prop.df &lt;- arrange(cities.df, desc(prop.dmg)) %&gt;% ungroup(state, countyname) %&gt;%
      mutate(rank = seq_len(length(prop.dmg)),
                prop.dmg = dollar(prop.dmg),
                crop.dmg = dollar(crop.dmg)
      )

kable(cities.prop.df[1:10, c(7,1:6)])</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">rank</th>
<th align="left">state</th>
<th align="left">countyname</th>
<th align="right">fatalities</th>
<th align="right">injuries</th>
<th align="left">prop.dmg</th>
<th align="left">crop.dmg</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="left">CA</td>
<td align="left">NAPA</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="left">$115,116,385,000</td>
<td align="left">$66,900,000</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="left">LA</td>
<td align="left">LAZ040</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="left">$31,316,850,000</td>
<td align="left">$0</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="left">LA</td>
<td align="left">LAZ034</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="left">$17,152,118,400</td>
<td align="left">$178,330,000</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="left">MS</td>
<td align="left">MSZ080</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="left">$11,264,195,000</td>
<td align="left">$0</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="left">FL</td>
<td align="left">FLZ068</td>
<td align="right">19</td>
<td align="right">16</td>
<td align="left">$10,367,010,000</td>
<td align="left">$1,047,000,000</td>
</tr>
<tr class="even">
<td align="right">6</td>
<td align="left">FL</td>
<td align="left">FLZ001</td>
<td align="right">33</td>
<td align="right">0</td>
<td align="left">$9,686,320,000</td>
<td align="left">$87,800,000</td>
</tr>
<tr class="odd">
<td align="right">7</td>
<td align="left">MS</td>
<td align="left">MSZ068</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="left">$7,375,405,000</td>
<td align="left">$0</td>
</tr>
<tr class="even">
<td align="right">8</td>
<td align="left">TX</td>
<td align="left">TXZ163</td>
<td align="right">116</td>
<td align="right">3</td>
<td align="left">$6,131,681,000</td>
<td align="left">$270,200,000</td>
</tr>
<tr class="odd">
<td align="right">9</td>
<td align="left">MS</td>
<td align="left">MSZ018</td>
<td align="right">17</td>
<td align="right">104</td>
<td align="left">$5,908,768,000</td>
<td align="left">$1,514,706,500</td>
</tr>
<tr class="even">
<td align="right">10</td>
<td align="left">FL</td>
<td align="left">FLZ055</td>
<td align="right">9</td>
<td align="right">786</td>
<td align="left">$5,424,027,000</td>
<td align="left">$292,000,000</td>
</tr>
</tbody>
</table>
<pre class="r"><code>worst.prop.city.county &lt;- cities.prop.df$countyname[1]
worst.prop.city.st &lt;- cities.prop.df$state[1]
worst.prop.city.count &lt;- cities.prop.df$prop.dmg[1]</code></pre>
<p>The county with the biggest property losses is <strong>NAPA, in CA, with $115,116,385,000 in losses.</strong></p>
</div>
<div id="worst-crops-losses" class="section level2">
<h2><span class="header-section-number">5.4</span> Worst crops losses</h2>
<pre class="r"><code>rm(cities.prop.df) # house cleanning


cities.crop.df &lt;- arrange(cities.df, desc(crop.dmg)) %&gt;% ungroup(state, countyname) %&gt;%
      mutate(rank = seq_len(length(crop.dmg)),
                prop.dmg = dollar(prop.dmg),
                crop.dmg = dollar(crop.dmg)
      )

kable(cities.crop.df[1:10, c(7,1:6)])</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">rank</th>
<th align="left">state</th>
<th align="left">countyname</th>
<th align="right">fatalities</th>
<th align="right">injuries</th>
<th align="left">prop.dmg</th>
<th align="left">crop.dmg</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="left">IL</td>
<td align="left">ADAMS</td>
<td align="right">0</td>
<td align="right">23</td>
<td align="left">$5,009,087,550</td>
<td align="left">$5,000,084,000</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="left">MS</td>
<td align="left">MSZ001</td>
<td align="right">4</td>
<td align="right">5</td>
<td align="left">$2,643,000</td>
<td align="left">$5,000,000,000</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="left">TX</td>
<td align="left">TXZ091</td>
<td align="right">69</td>
<td align="right">224</td>
<td align="left">$182,509,000</td>
<td align="left">$2,422,471,000</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="left">TX</td>
<td align="left">TXZ021</td>
<td align="right">2</td>
<td align="right">4</td>
<td align="left">$12,450,000</td>
<td align="left">$1,845,050,000</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="left">IA</td>
<td align="left">IAZ004</td>
<td align="right">10</td>
<td align="right">9</td>
<td align="left">$737,543,460</td>
<td align="left">$1,579,805,100</td>
</tr>
<tr class="even">
<td align="right">6</td>
<td align="left">MS</td>
<td align="left">MSZ018</td>
<td align="right">17</td>
<td align="right">104</td>
<td align="left">$5,908,768,000</td>
<td align="left">$1,514,706,500</td>
</tr>
<tr class="odd">
<td align="right">7</td>
<td align="left">FL</td>
<td align="left">FLZ068</td>
<td align="right">19</td>
<td align="right">16</td>
<td align="left">$10,367,010,000</td>
<td align="left">$1,047,000,000</td>
</tr>
<tr class="even">
<td align="right">8</td>
<td align="left">GA</td>
<td align="left">GAZ001</td>
<td align="right">20</td>
<td align="right">29</td>
<td align="left">$158,011,850</td>
<td align="left">$926,260,000</td>
</tr>
<tr class="odd">
<td align="right">9</td>
<td align="left">NE</td>
<td align="left">NEZ039</td>
<td align="right">4</td>
<td align="right">14</td>
<td align="left">$22,057,020</td>
<td align="left">$771,550,000</td>
</tr>
<tr class="even">
<td align="right">10</td>
<td align="left">NC</td>
<td align="left">NCZ029</td>
<td align="right">29</td>
<td align="right">201</td>
<td align="left">$1,940,635,500</td>
<td align="left">$768,600,000</td>
</tr>
</tbody>
</table>
<pre class="r"><code>worst.crop.city.county &lt;- cities.crop.df$countyname[1]
worst.crop.city.st &lt;- cities.crop.df$state[1]
worst.crop.city.count &lt;- cities.crop.df$crop.dmg[1]</code></pre>
<p>The county with the biggest croperty losses is <strong>ADAMS, in IL, with $5,000,084,000 in losses.</strong></p>
</div>
</div>
<div id="results" class="section level1">
<h1><span class="header-section-number">6</span> Results</h1>
<div id="population-health" class="section level2">
<h2><span class="header-section-number">6.1</span> Population Health</h2>
<pre class="r"><code># plist &lt;- list(plt.fatal.single, plt.fatal.all, plt.inj.single, plt.inj.all)
# n &lt;- length(plist)
# nCol &lt;- floor(sqrt(n))
# do.call(&quot;grid.arrange&quot;, c(plist, ncol=nCol))

grid.arrange(plt.fatal.single, plt.fatal.all, plt.inj.single, plt.inj.all, 
             nrow=2, ncol=2,
             bottom=&quot;Health impact&quot;)
grid.rect(gp=gpar(fill=NA))</code></pre>
<p><img src="readme_files/figure-html/health-plot-1.png" width="960" /></p>
<p>The single most fatal event was a <strong>HEAT, that occurred in IL, ILZ003, on 1995-07-12, killing 583 people.</strong></p>
<p>The most fatal event along the time is the <strong>TORNADO. It has killed 5636 people until now.</strong></p>
<p>The single most injuring event was a <strong>TORNADO, that occurred in TX, WICHITA, on 1979-04-10, injuring 1700 people.</strong></p>
<p>The most injuring event along the time is the <strong>TORNADO. It has injuried 91407 people until now.</strong></p>
</div>
<div id="economic-damages" class="section level2">
<h2><span class="header-section-number">6.2</span> Economic Damages</h2>
<pre class="r"><code>grid.arrange(plt.prop.single, plt.prop.all,
             plt.crop.single, plt.crop.all,
             nrow=2, ncol=2,
             bottom=&quot;Economic impact&quot;)
grid.rect(gp=gpar(fill=NA))</code></pre>
<p><img src="readme_files/figure-html/economic-plot-1.png" width="960" /></p>
<p>The single most economic damaging event to properties was a <strong>FLOOD, that occurred in CA, NAPA, on 2006-01-01, causing U$ $115,000,000,000 in losses</strong>.</p>
<p>The most property damaging event along the time is the <strong>FLOOD. It has caused $168,258,894,238 in losses.</strong></p>
<p>The single most economic damaging event to crops was a <strong>FLOOD, that occurred in IL, ADAMS, on 1993-08-31, causing U$ $5,000,000,000 in losses</strong>.</p>
<p>The most crop damaging event along the time is the <strong>DROUGHT. It has caused $13,972,581,000 in losses.</strong></p>
</div>
<div id="most-aflicted-locations-1" class="section level2">
<h2><span class="header-section-number">6.3</span> Most aflicted locations</h2>
<p>The county with the biggest fatality count is <strong>ILZ003, in IL, with 605 people killed.</strong></p>
<p>The county with the biggest injuries count is <strong>WICHITA, in TX, with 1852 people injuried.</strong></p>
<p>The county with the biggest property losses is <strong>NAPA, in CA, with $115,116,385,000 in losses.</strong></p>
<p>The county with the biggest croperty losses is <strong>ADAMS, in IL, with $5,000,084,000 in losses.</strong></p>
</div>
<div id="distribution-of-data" class="section level2">
<h2><span class="header-section-number">6.4</span> Distribution of data</h2>
<pre class="r"><code>grid.arrange(plt.distr.fatal0, plt.distr.fatal1, plt.distr.inj0, plt.distr.inj1, 
             nrow=1, ncol=4, 
             bottom=&quot;Population distribution - fatalities and injuries&quot;)
grid.rect(gp=gpar(fill=NA))             </code></pre>
<p><img src="readme_files/figure-html/distribution-1.png" width="960" /></p>
<pre class="r"><code>grid.arrange(plt.distr.prop0, plt.distr.prop1, plt.distr.crop0, plt.distr.crop1, 
             nrow=1, ncol=4, 
             bottom=&quot;Population distribution - property and crops losses&quot;)
grid.rect(gp=gpar(fill=NA))   </code></pre>
<p><img src="readme_files/figure-html/distribution-2.png" width="960" /></p>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
